window.BOLAO_DATA = {
  "updatedLabel": "Teste com dados correntes da planilha até 25/jun/2026 + mata-mata Match 73–104",
  "entryFee": 5,
  "prizes": {
    "first": 0.7,
    "second": 0.2,
    "third": 0.1
  },
  "flags": {
    "Mexico": "🇲🇽",
    "South Africa": "🇿🇦",
    "South Korea": "🇰🇷",
    "Czechia": "🇨🇿",
    "Canada": "🇨🇦",
    "Bosnia and Herzegovina": "🇧🇦",
    "Qatar": "🇶🇦",
    "Switzerland": "🇨🇭",
    "Brazil": "🇧🇷",
    "Morocco": "🇲🇦",
    "Haiti": "🇭🇹",
    "Scotland": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
    "United States": "🇺🇸",
    "Paraguay": "🇵🇾",
    "Australia": "🇦🇺",
    "Turkey": "🇹🇷",
    "Germany": "🇩🇪",
    "Curacao": "🇨🇼",
    "Ivory Coast": "🇨🇮",
    "Ecuador": "🇪🇨",
    "Netherlands": "🇳🇱",
    "Japan": "🇯🇵",
    "Sweden": "🇸🇪",
    "Tunisia": "🇹🇳",
    "Belgium": "🇧🇪",
    "Egypt": "🇪🇬",
    "Iran": "🇮🇷",
    "New Zealand": "🇳🇿",
    "Spain": "🇪🇸",
    "Cape Verde": "🇨🇻",
    "Saudi Arabia": "🇸🇦",
    "Uruguay": "🇺🇾",
    "France": "🇫🇷",
    "Senegal": "🇸🇳",
    "Iraq": "🇮🇶",
    "Norway": "🇳🇴",
    "Argentina": "🇦🇷",
    "Algeria": "🇩🇿",
    "Austria": "🇦🇹",
    "Jordan": "🇯🇴",
    "Portugal": "🇵🇹",
    "DR Congo": "🇨🇩",
    "Uzbekistan": "🇺🇿",
    "Colombia": "🇨🇴",
    "England": "🏴",
    "Croatia": "🇭🇷",
    "Ghana": "🇬🇭",
    "Panama": "🇵🇦"
  },
  "groupMatches": [
    {
      "match": "GS-01",
      "phase": "Fase de grupos",
      "date": "2026-06-11",
      "group": "A",
      "teamA": "Mexico",
      "teamB": "South Africa",
      "goalsA": 2,
      "goalsB": 0,
      "winner": "Mexico",
      "status": "Final"
    },
    {
      "match": "GS-02",
      "phase": "Fase de grupos",
      "date": "2026-06-11",
      "group": "A",
      "teamA": "South Korea",
      "teamB": "Czechia",
      "goalsA": 2,
      "goalsB": 1,
      "winner": "South Korea",
      "status": "Final"
    },
    {
      "match": "GS-03",
      "phase": "Fase de grupos",
      "date": "2026-06-12",
      "group": "B",
      "teamA": "Canada",
      "teamB": "Bosnia and Herzegovina",
      "goalsA": 1,
      "goalsB": 1,
      "winner": "Empate",
      "status": "Final"
    },
    {
      "match": "GS-04",
      "phase": "Fase de grupos",
      "date": "2026-06-12",
      "group": "D",
      "teamA": "United States",
      "teamB": "Paraguay",
      "goalsA": 4,
      "goalsB": 1,
      "winner": "United States",
      "status": "Final"
    },
    {
      "match": "GS-05",
      "phase": "Fase de grupos",
      "date": "2026-06-13",
      "group": "B",
      "teamA": "Qatar",
      "teamB": "Switzerland",
      "goalsA": 1,
      "goalsB": 1,
      "winner": "Empate",
      "status": "Final"
    },
    {
      "match": "GS-06",
      "phase": "Fase de grupos",
      "date": "2026-06-13",
      "group": "C",
      "teamA": "Brazil",
      "teamB": "Morocco",
      "goalsA": 1,
      "goalsB": 1,
      "winner": "Empate",
      "status": "Final"
    },
    {
      "match": "GS-07",
      "phase": "Fase de grupos",
      "date": "2026-06-13",
      "group": "C",
      "teamA": "Haiti",
      "teamB": "Scotland",
      "goalsA": 0,
      "goalsB": 1,
      "winner": "Scotland",
      "status": "Final"
    },
    {
      "match": "GS-08",
      "phase": "Fase de grupos",
      "date": "2026-06-13",
      "group": "D",
      "teamA": "Australia",
      "teamB": "Türkiye",
      "goalsA": 2,
      "goalsB": 0,
      "winner": "Australia",
      "status": "Final"
    },
    {
      "match": "GS-09",
      "phase": "Fase de grupos",
      "date": "2026-06-14",
      "group": "E",
      "teamA": "Germany",
      "teamB": "Curaçao",
      "goalsA": 7,
      "goalsB": 1,
      "winner": "Germany",
      "status": "Final"
    },
    {
      "match": "GS-10",
      "phase": "Fase de grupos",
      "date": "2026-06-14",
      "group": "F",
      "teamA": "Netherlands",
      "teamB": "Japan",
      "goalsA": 2,
      "goalsB": 2,
      "winner": "Empate",
      "status": "Final"
    },
    {
      "match": "GS-11",
      "phase": "Fase de grupos",
      "date": "2026-06-14",
      "group": "E",
      "teamA": "Ivory Coast",
      "teamB": "Ecuador",
      "goalsA": 1,
      "goalsB": 0,
      "winner": "Ivory Coast",
      "status": "Final"
    },
    {
      "match": "GS-12",
      "phase": "Fase de grupos",
      "date": "2026-06-14",
      "group": "F",
      "teamA": "Sweden",
      "teamB": "Tunisia",
      "goalsA": 5,
      "goalsB": 1,
      "winner": "Sweden",
      "status": "Final"
    },
    {
      "match": "GS-13",
      "phase": "Fase de grupos",
      "date": "2026-06-15",
      "group": "H",
      "teamA": "Spain",
      "teamB": "Cape Verde",
      "goalsA": 0,
      "goalsB": 0,
      "winner": "Empate",
      "status": "Final"
    },
    {
      "match": "GS-14",
      "phase": "Fase de grupos",
      "date": "2026-06-15",
      "group": "G",
      "teamA": "Belgium",
      "teamB": "Egypt",
      "goalsA": 1,
      "goalsB": 1,
      "winner": "Empate",
      "status": "Final"
    },
    {
      "match": "GS-15",
      "phase": "Fase de grupos",
      "date": "2026-06-15",
      "group": "H",
      "teamA": "Saudi Arabia",
      "teamB": "Uruguay",
      "goalsA": 1,
      "goalsB": 1,
      "winner": "Empate",
      "status": "Final"
    },
    {
      "match": "GS-16",
      "phase": "Fase de grupos",
      "date": "2026-06-15",
      "group": "G",
      "teamA": "Iran",
      "teamB": "New Zealand",
      "goalsA": 2,
      "goalsB": 2,
      "winner": "Empate",
      "status": "Final"
    },
    {
      "match": "GS-17",
      "phase": "Fase de grupos",
      "date": "2026-06-16",
      "group": "I",
      "teamA": "France",
      "teamB": "Senegal",
      "goalsA": 3,
      "goalsB": 1,
      "winner": "France",
      "status": "Final"
    },
    {
      "match": "GS-18",
      "phase": "Fase de grupos",
      "date": "2026-06-16",
      "group": "I",
      "teamA": "Iraq",
      "teamB": "Norway",
      "goalsA": 1,
      "goalsB": 4,
      "winner": "Norway",
      "status": "Final"
    },
    {
      "match": "GS-19",
      "phase": "Fase de grupos",
      "date": "2026-06-16",
      "group": "J",
      "teamA": "Argentina",
      "teamB": "Algeria",
      "goalsA": 3,
      "goalsB": 0,
      "winner": "Argentina",
      "status": "Final"
    },
    {
      "match": "GS-20",
      "phase": "Fase de grupos",
      "date": "2026-06-16",
      "group": "J",
      "teamA": "Austria",
      "teamB": "Jordan",
      "goalsA": 3,
      "goalsB": 1,
      "winner": "Austria",
      "status": "Final"
    },
    {
      "match": "GS-21",
      "phase": "Fase de grupos",
      "date": "2026-06-17",
      "group": "K",
      "teamA": "Portugal",
      "teamB": "DR Congo",
      "goalsA": 1,
      "goalsB": 1,
      "winner": "Empate",
      "status": "Final"
    },
    {
      "match": "GS-22",
      "phase": "Fase de grupos",
      "date": "2026-06-17",
      "group": "L",
      "teamA": "England",
      "teamB": "Croatia",
      "goalsA": 4,
      "goalsB": 2,
      "winner": "England",
      "status": "Final"
    },
    {
      "match": "GS-23",
      "phase": "Fase de grupos",
      "date": "2026-06-17",
      "group": "L",
      "teamA": "Ghana",
      "teamB": "Panama",
      "goalsA": 1,
      "goalsB": 0,
      "winner": "Ghana",
      "status": "Final"
    },
    {
      "match": "GS-24",
      "phase": "Fase de grupos",
      "date": "2026-06-17",
      "group": "K",
      "teamA": "Uzbekistan",
      "teamB": "Colombia",
      "goalsA": 1,
      "goalsB": 3,
      "winner": "Colombia",
      "status": "Final"
    },
    {
      "match": "GS-25",
      "phase": "Fase de grupos",
      "date": "2026-06-18",
      "group": "A",
      "teamA": "Czechia",
      "teamB": "South Africa",
      "goalsA": 1,
      "goalsB": 1,
      "winner": "Empate",
      "status": "Final"
    },
    {
      "match": "GS-26",
      "phase": "Fase de grupos",
      "date": "2026-06-18",
      "group": "B",
      "teamA": "Switzerland",
      "teamB": "Bosnia and Herzegovina",
      "goalsA": 4,
      "goalsB": 1,
      "winner": "Switzerland",
      "status": "Final"
    },
    {
      "match": "GS-27",
      "phase": "Fase de grupos",
      "date": "2026-06-18",
      "group": "B",
      "teamA": "Canada",
      "teamB": "Qatar",
      "goalsA": 6,
      "goalsB": 0,
      "winner": "Canada",
      "status": "Final"
    },
    {
      "match": "GS-28",
      "phase": "Fase de grupos",
      "date": "2026-06-18",
      "group": "A",
      "teamA": "Mexico",
      "teamB": "South Korea",
      "goalsA": 1,
      "goalsB": 0,
      "winner": "Mexico",
      "status": "Final"
    },
    {
      "match": "GS-29",
      "phase": "Fase de grupos",
      "date": "2026-06-19",
      "group": "D",
      "teamA": "United States",
      "teamB": "Australia",
      "goalsA": 2,
      "goalsB": 0,
      "winner": "United States",
      "status": "Final"
    },
    {
      "match": "GS-30",
      "phase": "Fase de grupos",
      "date": "2026-06-19",
      "group": "C",
      "teamA": "Scotland",
      "teamB": "Morocco",
      "goalsA": 0,
      "goalsB": 1,
      "winner": "Morocco",
      "status": "Final"
    },
    {
      "match": "GS-31",
      "phase": "Fase de grupos",
      "date": "2026-06-19",
      "group": "C",
      "teamA": "Brazil",
      "teamB": "Haiti",
      "goalsA": 3,
      "goalsB": 0,
      "winner": "Brazil",
      "status": "Final"
    },
    {
      "match": "GS-32",
      "phase": "Fase de grupos",
      "date": "2026-06-19",
      "group": "D",
      "teamA": "Türkiye",
      "teamB": "Paraguay",
      "goalsA": 0,
      "goalsB": 1,
      "winner": "Paraguay",
      "status": "Final"
    },
    {
      "match": "GS-33",
      "phase": "Fase de grupos",
      "date": "2026-06-20",
      "group": "F",
      "teamA": "Netherlands",
      "teamB": "Sweden",
      "goalsA": 5,
      "goalsB": 1,
      "winner": "Netherlands",
      "status": "Final"
    },
    {
      "match": "GS-34",
      "phase": "Fase de grupos",
      "date": "2026-06-20",
      "group": "E",
      "teamA": "Germany",
      "teamB": "Ivory Coast",
      "goalsA": 2,
      "goalsB": 1,
      "winner": "Germany",
      "status": "Final"
    },
    {
      "match": "GS-35",
      "phase": "Fase de grupos",
      "date": "2026-06-20",
      "group": "E",
      "teamA": "Ecuador",
      "teamB": "Curaçao",
      "goalsA": 0,
      "goalsB": 0,
      "winner": "Empate",
      "status": "Final"
    },
    {
      "match": "GS-36",
      "phase": "Fase de grupos",
      "date": "2026-06-20",
      "group": "F",
      "teamA": "Tunisia",
      "teamB": "Japan",
      "goalsA": 0,
      "goalsB": 4,
      "winner": "Japan",
      "status": "Final"
    },
    {
      "match": "GS-37",
      "phase": "Fase de grupos",
      "date": "2026-06-21",
      "group": "H",
      "teamA": "Spain",
      "teamB": "Saudi Arabia",
      "goalsA": 4,
      "goalsB": 0,
      "winner": "Spain",
      "status": "Final"
    },
    {
      "match": "GS-38",
      "phase": "Fase de grupos",
      "date": "2026-06-21",
      "group": "G",
      "teamA": "Belgium",
      "teamB": "Iran",
      "goalsA": 0,
      "goalsB": 0,
      "winner": "Empate",
      "status": "Final"
    },
    {
      "match": "GS-39",
      "phase": "Fase de grupos",
      "date": "2026-06-21",
      "group": "H",
      "teamA": "Uruguay",
      "teamB": "Cape Verde",
      "goalsA": 2,
      "goalsB": 2,
      "winner": "Empate",
      "status": "Final"
    },
    {
      "match": "GS-40",
      "phase": "Fase de grupos",
      "date": "2026-06-21",
      "group": "G",
      "teamA": "New Zealand",
      "teamB": "Egypt",
      "goalsA": 1,
      "goalsB": 3,
      "winner": "Egypt",
      "status": "Final"
    },
    {
      "match": "GS-41",
      "phase": "Fase de grupos",
      "date": "2026-06-22",
      "group": "J",
      "teamA": "Argentina",
      "teamB": "Austria",
      "goalsA": 2,
      "goalsB": 0,
      "winner": "Argentina",
      "status": "Final"
    },
    {
      "match": "GS-42",
      "phase": "Fase de grupos",
      "date": "2026-06-22",
      "group": "I",
      "teamA": "France",
      "teamB": "Iraq",
      "goalsA": 3,
      "goalsB": 0,
      "winner": "France",
      "status": "Final"
    },
    {
      "match": "GS-43",
      "phase": "Fase de grupos",
      "date": "2026-06-22",
      "group": "I",
      "teamA": "Norway",
      "teamB": "Senegal",
      "goalsA": 3,
      "goalsB": 2,
      "winner": "Norway",
      "status": "Final"
    },
    {
      "match": "GS-44",
      "phase": "Fase de grupos",
      "date": "2026-06-22",
      "group": "J",
      "teamA": "Jordan",
      "teamB": "Algeria",
      "goalsA": 1,
      "goalsB": 2,
      "winner": "Algeria",
      "status": "Final"
    },
    {
      "match": "GS-45",
      "phase": "Fase de grupos",
      "date": "2026-06-23",
      "group": "K",
      "teamA": "Portugal",
      "teamB": "Uzbekistan",
      "goalsA": 5,
      "goalsB": 0,
      "winner": "Portugal",
      "status": "Final"
    },
    {
      "match": "GS-46",
      "phase": "Fase de grupos",
      "date": "2026-06-23",
      "group": "L",
      "teamA": "England",
      "teamB": "Ghana",
      "goalsA": 0,
      "goalsB": 0,
      "winner": "Empate",
      "status": "Final"
    },
    {
      "match": "GS-47",
      "phase": "Fase de grupos",
      "date": "2026-06-23",
      "group": "L",
      "teamA": "Panama",
      "teamB": "Croatia",
      "goalsA": 0,
      "goalsB": 1,
      "winner": "Croatia",
      "status": "Final"
    },
    {
      "match": "GS-48",
      "phase": "Fase de grupos",
      "date": "2026-06-23",
      "group": "K",
      "teamA": "Colombia",
      "teamB": "DR Congo",
      "goalsA": 1,
      "goalsB": 0,
      "winner": "Colombia",
      "status": "Final"
    },
    {
      "match": "GS-49",
      "phase": "Fase de grupos",
      "date": "2026-06-24",
      "group": "B",
      "teamA": "Switzerland",
      "teamB": "Canada",
      "goalsA": 2,
      "goalsB": 1,
      "winner": "Switzerland",
      "status": "Final"
    },
    {
      "match": "GS-50",
      "phase": "Fase de grupos",
      "date": "2026-06-24",
      "group": "B",
      "teamA": "Bosnia and Herzegovina",
      "teamB": "Qatar",
      "goalsA": 3,
      "goalsB": 1,
      "winner": "Bosnia and Herzegovina",
      "status": "Final"
    },
    {
      "match": "GS-51",
      "phase": "Fase de grupos",
      "date": "2026-06-24",
      "group": "C",
      "teamA": "Scotland",
      "teamB": "Brazil",
      "goalsA": 0,
      "goalsB": 3,
      "winner": "Brazil",
      "status": "Final"
    },
    {
      "match": "GS-52",
      "phase": "Fase de grupos",
      "date": "2026-06-24",
      "group": "C",
      "teamA": "Morocco",
      "teamB": "Haiti",
      "goalsA": 4,
      "goalsB": 2,
      "winner": "Morocco",
      "status": "Final"
    },
    {
      "match": "GS-53",
      "phase": "Fase de grupos",
      "date": "2026-06-24",
      "group": "A",
      "teamA": "Czechia",
      "teamB": "Mexico",
      "goalsA": 0,
      "goalsB": 3,
      "winner": "Mexico",
      "status": "Final"
    },
    {
      "match": "GS-54",
      "phase": "Fase de grupos",
      "date": "2026-06-24",
      "group": "A",
      "teamA": "South Africa",
      "teamB": "South Korea",
      "goalsA": 1,
      "goalsB": 0,
      "winner": "South Africa",
      "status": "Final"
    },
    {
      "match": "GS-55",
      "phase": "Fase de grupos",
      "date": "2026-06-25",
      "group": "E",
      "teamA": "Ecuador",
      "teamB": "Germany",
      "goalsA": 2,
      "goalsB": 1,
      "winner": "Ecuador",
      "status": "Final"
    },
    {
      "match": "GS-56",
      "phase": "Fase de grupos",
      "date": "2026-06-25",
      "group": "E",
      "teamA": "Curaçao",
      "teamB": "Ivory Coast",
      "goalsA": 0,
      "goalsB": 2,
      "winner": "Ivory Coast",
      "status": "Final"
    },
    {
      "match": "GS-57",
      "phase": "Fase de grupos",
      "date": "2026-06-25",
      "group": "F",
      "teamA": "Japan",
      "teamB": "Sweden",
      "goalsA": 1,
      "goalsB": 1,
      "winner": "Empate",
      "status": "Final"
    },
    {
      "match": "GS-58",
      "phase": "Fase de grupos",
      "date": "2026-06-25",
      "group": "F",
      "teamA": "Tunisia",
      "teamB": "Netherlands",
      "goalsA": 1,
      "goalsB": 3,
      "winner": "Netherlands",
      "status": "Final"
    },
    {
      "match": "GS-59",
      "phase": "Fase de grupos",
      "date": "2026-06-25",
      "group": "D",
      "teamA": "Türkiye",
      "teamB": "United States",
      "goalsA": 3,
      "goalsB": 2,
      "winner": "Türkiye",
      "status": "Final"
    },
    {
      "match": "GS-60",
      "phase": "Fase de grupos",
      "date": "2026-06-25",
      "group": "D",
      "teamA": "Paraguay",
      "teamB": "Australia",
      "goalsA": 0,
      "goalsB": 0,
      "winner": "Empate",
      "status": "Final"
    },
    {
      "match": "GS-61",
      "phase": "Fase de grupos",
      "date": "2026-06-26",
      "group": "I",
      "teamA": "Norway",
      "teamB": "France",
      "goalsA": null,
      "goalsB": null,
      "winner": "",
      "status": "Scheduled"
    },
    {
      "match": "GS-62",
      "phase": "Fase de grupos",
      "date": "2026-06-26",
      "group": "I",
      "teamA": "Senegal",
      "teamB": "Iraq",
      "goalsA": null,
      "goalsB": null,
      "winner": "",
      "status": "Scheduled"
    },
    {
      "match": "GS-63",
      "phase": "Fase de grupos",
      "date": "2026-06-26",
      "group": "H",
      "teamA": "Cape Verde",
      "teamB": "Saudi Arabia",
      "goalsA": null,
      "goalsB": null,
      "winner": "",
      "status": "Scheduled"
    },
    {
      "match": "GS-64",
      "phase": "Fase de grupos",
      "date": "2026-06-26",
      "group": "H",
      "teamA": "Uruguay",
      "teamB": "Spain",
      "goalsA": null,
      "goalsB": null,
      "winner": "",
      "status": "Scheduled"
    },
    {
      "match": "GS-65",
      "phase": "Fase de grupos",
      "date": "2026-06-26",
      "group": "G",
      "teamA": "Egypt",
      "teamB": "Iran",
      "goalsA": null,
      "goalsB": null,
      "winner": "",
      "status": "Scheduled"
    },
    {
      "match": "GS-66",
      "phase": "Fase de grupos",
      "date": "2026-06-26",
      "group": "G",
      "teamA": "New Zealand",
      "teamB": "Belgium",
      "goalsA": null,
      "goalsB": null,
      "winner": "",
      "status": "Scheduled"
    },
    {
      "match": "GS-67",
      "phase": "Fase de grupos",
      "date": "2026-06-27",
      "group": "L",
      "teamA": "Panama",
      "teamB": "England",
      "goalsA": null,
      "goalsB": null,
      "winner": "",
      "status": "Scheduled"
    },
    {
      "match": "GS-68",
      "phase": "Fase de grupos",
      "date": "2026-06-27",
      "group": "L",
      "teamA": "Croatia",
      "teamB": "Ghana",
      "goalsA": null,
      "goalsB": null,
      "winner": "",
      "status": "Scheduled"
    },
    {
      "match": "GS-69",
      "phase": "Fase de grupos",
      "date": "2026-06-27",
      "group": "K",
      "teamA": "Colombia",
      "teamB": "Portugal",
      "goalsA": null,
      "goalsB": null,
      "winner": "",
      "status": "Scheduled"
    },
    {
      "match": "GS-70",
      "phase": "Fase de grupos",
      "date": "2026-06-27",
      "group": "K",
      "teamA": "DR Congo",
      "teamB": "Uzbekistan",
      "goalsA": null,
      "goalsB": null,
      "winner": "",
      "status": "Scheduled"
    },
    {
      "match": "GS-71",
      "phase": "Fase de grupos",
      "date": "2026-06-27",
      "group": "J",
      "teamA": "Algeria",
      "teamB": "Austria",
      "goalsA": null,
      "goalsB": null,
      "winner": "",
      "status": "Scheduled"
    },
    {
      "match": "GS-72",
      "phase": "Fase de grupos",
      "date": "2026-06-27",
      "group": "J",
      "teamA": "Jordan",
      "teamB": "Argentina",
      "goalsA": null,
      "goalsB": null,
      "winner": "",
      "status": "Scheduled"
    }
  ],
  "knockoutMatches": [
    {
      "match": "73",
      "phase": "Round of 32",
      "date": "2026-06-28",
      "group": "",
      "teamA": "South Africa",
      "teamB": "Canada",
      "goalsA": null,
      "goalsB": null,
      "winner": "",
      "status": "Scheduled"
    },
    {
      "match": "74",
      "phase": "Round of 32",
      "date": "2026-06-29",
      "group": "",
      "teamA": "Brazil",
      "teamB": "Japan",
      "goalsA": null,
      "goalsB": null,
      "winner": "",
      "status": "Scheduled"
    },
    {
      "match": "75",
      "phase": "Round of 32",
      "date": "2026-06-29",
      "group": "",
      "teamA": "Germany",
      "teamB": "3rd A/B/C/D/F",
      "goalsA": null,
      "goalsB": null,
      "winner": "",
      "status": "Scheduled"
    },
    {
      "match": "76",
      "phase": "Round of 32",
      "date": "2026-06-29",
      "group": "",
      "teamA": "Netherlands",
      "teamB": "Morocco",
      "goalsA": null,
      "goalsB": null,
      "winner": "",
      "status": "Scheduled"
    },
    {
      "match": "77",
      "phase": "Round of 32",
      "date": "2026-06-30",
      "group": "",
      "teamA": "Ivory Coast",
      "teamB": "2nd Group I",
      "goalsA": null,
      "goalsB": null,
      "winner": "",
      "status": "Scheduled"
    },
    {
      "match": "78",
      "phase": "Round of 32",
      "date": "2026-06-30",
      "group": "",
      "teamA": "1st Group I",
      "teamB": "3rd C/D/F/G/H",
      "goalsA": null,
      "goalsB": null,
      "winner": "",
      "status": "Scheduled"
    },
    {
      "match": "79",
      "phase": "Round of 32",
      "date": "2026-06-30",
      "group": "",
      "teamA": "Mexico",
      "teamB": "3rd C/E/F/H/I",
      "goalsA": null,
      "goalsB": null,
      "winner": "",
      "status": "Scheduled"
    },
    {
      "match": "80",
      "phase": "Round of 32",
      "date": "2026-07-01",
      "group": "",
      "teamA": "1st Group L",
      "teamB": "3rd E/H/I/J/K",
      "goalsA": null,
      "goalsB": null,
      "winner": "",
      "status": "Scheduled"
    },
    {
      "match": "81",
      "phase": "Round of 32",
      "date": "2026-07-01",
      "group": "",
      "teamA": "1st Group G",
      "teamB": "3rd A/E/H/I/J",
      "goalsA": null,
      "goalsB": null,
      "winner": "",
      "status": "Scheduled"
    },
    {
      "match": "82",
      "phase": "Round of 32",
      "date": "2026-07-01",
      "group": "",
      "teamA": "United States",
      "teamB": "Bosnia and Herzegovina",
      "goalsA": null,
      "goalsB": null,
      "winner": "",
      "status": "Scheduled"
    },
    {
      "match": "83",
      "phase": "Round of 32",
      "date": "2026-07-02",
      "group": "",
      "teamA": "1st Group H",
      "teamB": "2nd Group J",
      "goalsA": null,
      "goalsB": null,
      "winner": "",
      "status": "Scheduled"
    },
    {
      "match": "84",
      "phase": "Round of 32",
      "date": "2026-07-02",
      "group": "",
      "teamA": "2nd Group K",
      "teamB": "2nd Group L",
      "goalsA": null,
      "goalsB": null,
      "winner": "",
      "status": "Scheduled"
    },
    {
      "match": "85",
      "phase": "Round of 32",
      "date": "2026-07-02",
      "group": "",
      "teamA": "Switzerland",
      "teamB": "3rd E/F/G/I/J",
      "goalsA": null,
      "goalsB": null,
      "winner": "",
      "status": "Scheduled"
    },
    {
      "match": "86",
      "phase": "Round of 32",
      "date": "2026-07-03",
      "group": "",
      "teamA": "Australia",
      "teamB": "2nd Group G",
      "goalsA": null,
      "goalsB": null,
      "winner": "",
      "status": "Scheduled"
    },
    {
      "match": "87",
      "phase": "Round of 32",
      "date": "2026-07-03",
      "group": "",
      "teamA": "Argentina",
      "teamB": "2nd Group H",
      "goalsA": null,
      "goalsB": null,
      "winner": "",
      "status": "Scheduled"
    },
    {
      "match": "88",
      "phase": "Round of 32",
      "date": "2026-07-03",
      "group": "",
      "teamA": "1st Group K",
      "teamB": "3rd D/E/I/J/L",
      "goalsA": null,
      "goalsB": null,
      "winner": "",
      "status": "Scheduled"
    },
    {
      "match": "89",
      "phase": "Round of 16",
      "date": "2026-07-04",
      "group": "",
      "teamA": "Winner Match 73",
      "teamB": "Winner Match 75",
      "goalsA": null,
      "goalsB": null,
      "winner": "",
      "status": "Scheduled"
    },
    {
      "match": "90",
      "phase": "Round of 16",
      "date": "2026-07-04",
      "group": "",
      "teamA": "Winner Match 74",
      "teamB": "Winner Match 77",
      "goalsA": null,
      "goalsB": null,
      "winner": "",
      "status": "Scheduled"
    },
    {
      "match": "91",
      "phase": "Round of 16",
      "date": "2026-07-05",
      "group": "",
      "teamA": "Winner Match 76",
      "teamB": "Winner Match 78",
      "goalsA": null,
      "goalsB": null,
      "winner": "",
      "status": "Scheduled"
    },
    {
      "match": "92",
      "phase": "Round of 16",
      "date": "2026-07-05",
      "group": "",
      "teamA": "Winner Match 79",
      "teamB": "Winner Match 80",
      "goalsA": null,
      "goalsB": null,
      "winner": "",
      "status": "Scheduled"
    },
    {
      "match": "93",
      "phase": "Round of 16",
      "date": "2026-07-06",
      "group": "",
      "teamA": "Winner Match 83",
      "teamB": "Winner Match 84",
      "goalsA": null,
      "goalsB": null,
      "winner": "",
      "status": "Scheduled"
    },
    {
      "match": "94",
      "phase": "Round of 16",
      "date": "2026-07-06",
      "group": "",
      "teamA": "Winner Match 81",
      "teamB": "Winner Match 82",
      "goalsA": null,
      "goalsB": null,
      "winner": "",
      "status": "Scheduled"
    },
    {
      "match": "95",
      "phase": "Round of 16",
      "date": "2026-07-07",
      "group": "",
      "teamA": "Winner Match 86",
      "teamB": "Winner Match 88",
      "goalsA": null,
      "goalsB": null,
      "winner": "",
      "status": "Scheduled"
    },
    {
      "match": "96",
      "phase": "Round of 16",
      "date": "2026-07-07",
      "group": "",
      "teamA": "Winner Match 85",
      "teamB": "Winner Match 87",
      "goalsA": null,
      "goalsB": null,
      "winner": "",
      "status": "Scheduled"
    },
    {
      "match": "97",
      "phase": "Quarterfinal",
      "date": "2026-07-09",
      "group": "",
      "teamA": "Winner Match 89",
      "teamB": "Winner Match 90",
      "goalsA": null,
      "goalsB": null,
      "winner": "",
      "status": "Scheduled"
    },
    {
      "match": "98",
      "phase": "Quarterfinal",
      "date": "2026-07-10",
      "group": "",
      "teamA": "Winner Match 93",
      "teamB": "Winner Match 94",
      "goalsA": null,
      "goalsB": null,
      "winner": "",
      "status": "Scheduled"
    },
    {
      "match": "99",
      "phase": "Quarterfinal",
      "date": "2026-07-11",
      "group": "",
      "teamA": "Winner Match 91",
      "teamB": "Winner Match 92",
      "goalsA": null,
      "goalsB": null,
      "winner": "",
      "status": "Scheduled"
    },
    {
      "match": "100",
      "phase": "Quarterfinal",
      "date": "2026-07-11",
      "group": "",
      "teamA": "Winner Match 95",
      "teamB": "Winner Match 96",
      "goalsA": null,
      "goalsB": null,
      "winner": "",
      "status": "Scheduled"
    },
    {
      "match": "101",
      "phase": "Semifinal",
      "date": "2026-07-14",
      "group": "",
      "teamA": "Winner Match 97",
      "teamB": "Winner Match 98",
      "goalsA": null,
      "goalsB": null,
      "winner": "",
      "status": "Scheduled"
    },
    {
      "match": "102",
      "phase": "Semifinal",
      "date": "2026-07-15",
      "group": "",
      "teamA": "Winner Match 99",
      "teamB": "Winner Match 100",
      "goalsA": null,
      "goalsB": null,
      "winner": "",
      "status": "Scheduled"
    },
    {
      "match": "103",
      "phase": "3rd Place",
      "date": "2026-07-18",
      "group": "",
      "teamA": "Loser Match 101",
      "teamB": "Loser Match 102",
      "goalsA": null,
      "goalsB": null,
      "winner": "",
      "status": "Scheduled"
    },
    {
      "match": "104",
      "phase": "Final",
      "date": "2026-07-19",
      "group": "",
      "teamA": "Winner Match 101",
      "teamB": "Winner Match 102",
      "goalsA": null,
      "goalsB": null,
      "winner": "",
      "status": "Scheduled"
    }
  ],
  "rules": {
    "exactScore": 10,
    "advance": 5,
    "oneTeamGoals": 1,
    "maxPerMatch": 15
  },
  "bonus": {
    "champion": 25,
    "runnerUp": 15,
    "third": 10,
    "fourth": 5
  },
  "strength": {
    "Brazil": 94,
    "Argentina": 94,
    "France": 93,
    "Spain": 91,
    "England": 90,
    "Portugal": 89,
    "Germany": 88,
    "Netherlands": 87,
    "Uruguay": 84,
    "Colombia": 83,
    "Belgium": 82,
    "Switzerland": 80,
    "United States": 79,
    "Mexico": 78,
    "Morocco": 78,
    "Japan": 77,
    "Croatia": 77,
    "Senegal": 76,
    "Norway": 76,
    "Ecuador": 75,
    "Ivory Coast": 74,
    "Canada": 73,
    "Australia": 72,
    "Turkey": 72,
    "Ghana": 71,
    "Austria": 71,
    "South Korea": 70,
    "Czechia": 70,
    "Paraguay": 69,
    "Sweden": 69,
    "Egypt": 68,
    "Iran": 68,
    "South Africa": 66,
    "Bosnia and Herzegovina": 66,
    "Algeria": 66,
    "DR Congo": 64,
    "Panama": 63,
    "Scotland": 63,
    "Tunisia": 62,
    "Cape Verde": 61,
    "Saudi Arabia": 61,
    "New Zealand": 60,
    "Iraq": 60,
    "Uzbekistan": 59,
    "Jordan": 58,
    "Haiti": 56,
    "Qatar": 55,
    "Curacao": 54
  }
};
