"""
generate_audit_report.py — Bolão Ferrari Copa 2026

Generates a trilingual (pt-BR / en-US / es), professional-style technical audit report as a
static HTML file (bolao/audit-report.html), using LIVE production data pulled from Supabase.

Eduardo, 2026-07-18, the day before the Final (M104): "Antes dos resultados finais fazer uma
auditoria automática com relatório estilo kpmg, big 4 e adicionar no site como um pdf ou html e
colocar um link para visualização. Colocar o máximo de detalhes possíveis! A auditoria precisa
ser nas 3 linguagens só para deixar claro."

Design notes:
  - HTML, not PDF: no build step in this repo (see CLAUDE.md), no PDF library available in the
    environment, and Eduardo's own wording allowed either ("um pdf ou html"). The page is
    print-friendly (browser "Print to PDF" gives a PDF on demand, same pattern already used by
    the site's own receiptHtml()).
  - "Big 4 style" means the STRUCTURE and RIGOR of a professional audit report (scope statement,
    methodology, independent recomputation, findings, opinion, sign-off) — this report is NOT
    affiliated with, produced by, or endorsed by KPMG or any other accounting firm, and does not
    use their names/branding/logos. It is generated by the bolão's own automated verification
    system and says so plainly in the header.
  - Independent recomputation: the checks below deliberately do NOT call scoreEntry()-equivalent
    functions from send_result_email.py for the actual point/podium math — they re-derive it from
    raw picks + raw results in fresh code, then diff against send_result_email.py's own output.
    Catches bugs in the "official" implementation itself, not just bugs in this script.

Usage:
  python3 generate_audit_report.py
    Fetches the live production state from Supabase, runs every check, writes
    bolao/audit-report.html (relative to the repo root, i.e. this file's parent's parent).
"""

import json
import os
import re
import sys
from datetime import datetime, timezone

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import send_result_email as sre
import audit_scoring

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", ".."))
OUT_PATH = os.path.join(REPO_ROOT, "bolao", "copa2026", "audit-report.html")
PICKS_DETAIL_PATH = os.path.join(REPO_ROOT, "bolao", "copa2026", "audit-detail-picks.html")
GOVERNANCE_DETAIL_PATH = os.path.join(REPO_ROOT, "bolao", "copa2026", "audit-detail-governance.html")
GITHUB_REPO_URL = "https://github.com/ferrarilabs/ferrarilabs.github.io/blob/main"

PHASE_LABELS = {
    "Round of 32":  {"pt": "Oitavas de Final",       "en": "Round of 32",     "es": "Octavos de Final"},
    "Round of 16":  {"pt": "Rodada de 16",           "en": "Round of 16",     "es": "Ronda de 16"},
    "Quarterfinal": {"pt": "Quartas de Final",       "en": "Quarterfinal",    "es": "Cuartos de Final"},
    "Semifinal":    {"pt": "Semifinal",              "en": "Semifinal",       "es": "Semifinal"},
    "3rd Place":    {"pt": "Disputa de 3º Lugar",    "en": "3rd Place Match", "es": "Partido por el 3er Lugar"},
    "Final":        {"pt": "Final",                  "en": "Final",           "es": "Final"},
}


def _phase_for_mid(mid):
    m = int(mid)
    if 73 <= m <= 88:
        return "Round of 32"
    if 89 <= m <= 96:
        return "Round of 16"
    if 97 <= m <= 100:
        return "Quarterfinal"
    if 101 <= m <= 102:
        return "Semifinal"
    if m == 103:
        return "3rd Place"
    return "Final"


DETAIL_PAGE_STYLE = """
  :root { --green:#0d7a3f; --gold:#b45309; --border:#dde3e8; --bg:#f4f7fb; --bad:#b91c1c; }
  * { box-sizing:border-box; }
  body { font-family:Arial,Helvetica,sans-serif; background:var(--bg); color:#161b1f; margin:0; padding:0 12px 60px; }
  .doc { max-width:1200px; margin:0 auto; }
  .lang-bar { position:sticky; top:0; background:#fff; border-bottom:1px solid var(--border); padding:12px 8px; margin-bottom:8px; display:flex; gap:8px; flex-wrap:wrap; justify-content:center; z-index:10; }
  .lang-bar button, .lang-bar a.backlink { font-family:Arial,sans-serif; font-size:13px; font-weight:700; padding:8px 16px; border-radius:20px; border:1px solid var(--border); background:#fff; cursor:pointer; white-space:nowrap; text-decoration:none; color:#161b1f; }
  .lang-bar button.active { background:var(--green); color:#fff; border-color:var(--green); }
  @media (max-width:420px) { .lang-bar button, .lang-bar a.backlink { font-size:12px; padding:8px 12px; } }
  .page-header { background:#fff; border:1px solid var(--border); border-radius:14px; padding:22px 26px; margin:16px 0 20px; box-shadow:0 4px 24px #0001; }
  .page-header h1 { margin:0 0 8px; font-size:22px; }
  .page-header p { font-size:13px; color:#444; margin:4px 0; }
  .entry-block { background:#fff; border:1px solid var(--border); border-radius:12px; margin-bottom:12px; box-shadow:0 2px 10px #0001; }
  .entry-block summary { cursor:pointer; padding:14px 18px; font-weight:700; font-size:14.5px; display:flex; justify-content:space-between; align-items:center; gap:10px; flex-wrap:wrap; list-style:none; }
  .entry-block summary::-webkit-details-marker { display:none; }
  .entry-block summary::before { content:"▶"; font-size:11px; margin-right:8px; color:#888; }
  .entry-block[open] summary::before { content:"▼"; }
  .entry-badge { font-size:12px; font-weight:800; background:#d1fae5; color:#065f46; padding:3px 10px; border-radius:20px; }
  .entry-badge.warn { background:#fee2e2; color:var(--bad); }
  .entry-body { padding:0 18px 16px; }
  .table-scroll { overflow-x:auto; }
  table.detail-table { width:100%; min-width:640px; border-collapse:collapse; font-size:12.5px; }
  table.detail-table th { background:#f1f5f9; text-align:left; padding:6px 8px; border-bottom:2px solid var(--border); position:sticky; top:52px; }
  table.detail-table td { padding:5px 8px; border-bottom:1px solid #eef1f4; }
  table.detail-table td.num { text-align:center; font-weight:700; }
  .idx-list { columns:2; gap:24px; font-size:13px; }
  @media (max-width:640px) { .idx-list { columns:1; } }
  .idx-list a { color:#0d7a3f; text-decoration:none; }
  .anomaly-box { background:#fef3c7; border:1px solid #f59e0b; border-radius:10px; padding:12px 16px; margin-bottom:16px; font-size:13px; }
  code.small { background:#f1f5f9; padding:1px 5px; border-radius:4px; font-size:.92em; }
"""

DETAIL_PAGE_SCRIPT = """
(function() {
  var buttons = document.querySelectorAll('[data-setlang]');
  buttons.forEach(function(btn) {
    btn.addEventListener('click', function() {
      var lang = btn.getAttribute('data-setlang');
      document.querySelectorAll('[data-lang]').forEach(function(el) {
        el.classList.toggle('lang-active', el.getAttribute('data-lang') === lang);
      });
      buttons.forEach(function(b) { b.classList.toggle('active', b === btn); });
      document.documentElement.lang = lang === 'pt' ? 'pt-BR' : lang === 'es' ? 'es' : 'en-US';
    });
  });
})();
"""


# ── Independent recomputation (fresh code, not reusing sre's scoring logic) ───────────────────

def _resolve_slot_indep(slot, results, cache):
    m = re.match(r'^([WL])(\d+)$', str(slot))
    if not m:
        return slot
    prefix, mid = m.group(1), m.group(2)
    if mid not in cache:
        r = results.get(mid)
        if not r or not r.get("advanceSide"):
            cache[mid] = (None, None)
        else:
            tA_raw, tB_raw = sre.MATCH_TEAMS[mid]
            a = _resolve_slot_indep(tA_raw, results, cache)
            b = _resolve_slot_indep(tB_raw, results, cache)
            cache[mid] = (None, None) if (a is None or b is None) else ((b, a) if r["advanceSide"] == "B" else (a, b))
    winner, loser = cache[mid]
    if winner is None:
        return None
    return winner if prefix == "W" else loser


def _parse_indep(v):
    s = str(v).strip() if v is not None else ""
    if not re.match(r'^\d+$', s):
        return None
    n = int(s)
    return n if 0 <= n <= 20 else None


def independent_match_points(pick, result):
    if not pick or not result or not result.get("advanceSide"):
        return 0
    pA, pB = _parse_indep(pick.get("goalsA")), _parse_indep(pick.get("goalsB"))
    rA, rB = _parse_indep(result.get("goalsA")), _parse_indep(result.get("goalsB"))
    if pA is None or pB is None or rA is None or rB is None:
        return 0
    pts = 0
    if pA == rA and pB == rB:
        pts += 10
    else:
        if pA == rA:
            pts += 1
        if pB == rB:
            pts += 1
    if pick.get("advanceSide") == result.get("advanceSide"):
        pts += 5
    return pts


def independent_real_podium(results):
    """Champion/runnerUp (once M104 is decided) and/or third/fourth (once M103 is decided),
    independently -- NOT gated on both being known. Mirrors the fix in
    send_result_email.py's _podium_from_results()/app.js's podiumFromResults() (2026-07-19):
    requiring both before returning anything meant a real M103-only bonus (Simone Hirle #4,
    Gabriel Ferrari) was silently withheld. Kept this independent copy in sync with that same
    fix so the audit's own recomputation doesn't flag a false mismatch against the corrected
    official score."""
    cache = {}
    champion = runner_up = None
    fin = results.get("104")
    if fin and fin.get("advanceSide"):
        fA_raw, fB_raw = sre.MATCH_TEAMS["104"]
        a, b = _resolve_slot_indep(fA_raw, results, cache), _resolve_slot_indep(fB_raw, results, cache)
        champion, runner_up = (b, a) if fin["advanceSide"] == "B" else (a, b)
    third = fourth = None
    trd = results.get("103")
    if trd and trd.get("advanceSide"):
        tA_raw, tB_raw = sre.MATCH_TEAMS["103"]
        ta, tb = _resolve_slot_indep(tA_raw, results, cache), _resolve_slot_indep(tB_raw, results, cache)
        third, fourth = (tb, ta) if trd["advanceSide"] == "B" else (ta, tb)
    if not champion and not third:
        return None
    return {"champion": champion, "runnerUp": runner_up, "third": third, "fourth": fourth}


def independent_entry_predicted_podium(entry):
    picks = entry.get("picks") or {}
    winners, losers = {}, {}

    def resolve_pred(slot):
        m = re.match(r'^([WL])(\d+)$', str(slot))
        if not m:
            return slot
        prefix, mid = m.group(1), m.group(2)
        return (winners.get(mid) if prefix == "W" else losers.get(mid)) or slot

    for mid in sorted(sre.MATCH_TEAMS.keys(), key=int):
        tA_raw, tB_raw = sre.MATCH_TEAMS[mid]
        a, b = resolve_pred(tA_raw), resolve_pred(tB_raw)
        p = picks.get(mid)
        if p and p.get("advanceSide") == "A":
            winners[mid], losers[mid] = a, b
        elif p and p.get("advanceSide") == "B":
            winners[mid], losers[mid] = b, a

    champion = runner_up = third = fourth = None
    fin_pick, trd_pick = picks.get("104"), picks.get("103")
    if fin_pick:
        a, b = resolve_pred(sre.MATCH_TEAMS["104"][0]), resolve_pred(sre.MATCH_TEAMS["104"][1])
        champion, runner_up = (b, a) if fin_pick.get("advanceSide") == "B" else (a, b)
    if trd_pick:
        a, b = resolve_pred(sre.MATCH_TEAMS["103"][0]), resolve_pred(sre.MATCH_TEAMS["103"][1])
        third, fourth = (b, a) if trd_pick.get("advanceSide") == "B" else (a, b)
    return {"champion": champion, "runnerUp": runner_up, "third": third, "fourth": fourth}


def independent_entry_total(entry, results):
    picks = entry.get("picks") or {}
    total = sum(independent_match_points(picks.get(mid), results.get(mid)) for mid in sre.MATCH_TEAMS)
    real_pod = independent_real_podium(results)
    if real_pod:
        pred = independent_entry_predicted_podium(entry)
        if pred["champion"] and pred["champion"] == real_pod["champion"]:
            total += 25
        if pred["runnerUp"] and pred["runnerUp"] == real_pod["runnerUp"]:
            total += 15
        if pred["third"] and real_pod["third"] and pred["third"] == real_pod["third"]:
            total += 10
        if pred["fourth"] and real_pod["fourth"] and pred["fourth"] == real_pod["fourth"]:
            total += 5
    return total


def independent_exact_count(entry, results):
    picks = entry.get("picks") or {}
    n = 0
    for mid, result in results.items():
        if not result.get("advanceSide"):
            continue
        pick = picks.get(mid)
        if not pick:
            continue
        pA, pB = _parse_indep(pick.get("goalsA")), _parse_indep(pick.get("goalsB"))
        rA, rB = _parse_indep(result.get("goalsA")), _parse_indep(result.get("goalsB"))
        if None not in (pA, pB, rA, rB) and pA == rA and pB == rB:
            n += 1
    return n


# ── Finding record ──────────────────────────────────────────────────────────────────────────

class Finding:
    def __init__(self, key, status, title, detail):
        self.key = key
        self.status = status  # "pass" | "remediated" | "info"
        self.title = title      # {"pt":..., "en":..., "es":...}
        self.detail = detail    # {"pt":..., "en":..., "es":...} — may contain HTML


def esc(s):
    return (str(s).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;"))


def run_checks(state):
    findings = []
    results_all = state.get("results", {}) or {}
    locked_results = {k: v for k, v in results_all.items() if v and v.get("advanceSide")}
    deleted = set(state.get("deletedIds", []))
    entries = [e for e in state.get("entries", [])
               if e.get("id") not in deleted and not (e.get("diagnostics") or {}).get("demo")]
    demo_count = sum(1 for e in state.get("entries", []) if (e.get("diagnostics") or {}).get("demo"))

    # A — Scoring formula constants vs the site's own CONFIG mirror
    expected_scoring = {"exactScore": 10, "advance": 5, "oneTeamGoals": 1}
    expected_bonus = {"champion": 25, "runnerUp": 15, "third": 10, "fourth": 5}
    expected_prizes = {"first": 0.70, "second": 0.20, "third": 0.10}
    scoring_ok = sre.SCORING == expected_scoring
    bonus_ok = sre.BONUS == expected_bonus
    prizes_ok = sre.PRIZES == expected_prizes and abs(sum(expected_prizes.values()) - 1.0) < 1e-9
    findings.append(Finding(
        "scoring-constants", "pass" if (scoring_ok and bonus_ok and prizes_ok) else "info",
        {"pt": "A. Integridade da fórmula de pontuação", "en": "A. Scoring formula integrity", "es": "A. Integridad de la fórmula de puntuación"},
        {
            "pt": f"""Valores usados pelo pipeline de e-mail (<code>send_result_email.py</code>) comparados contra os valores esperados, cadastrados de forma independente neste script de auditoria (não copiados de <code>config.js</code> diretamente):
              <ul><li>Placar exato: {sre.SCORING['exactScore']} pts (esperado {expected_scoring['exactScore']}) — {'OK' if sre.SCORING['exactScore']==expected_scoring['exactScore'] else 'DIVERGENTE'}</li>
              <li>Gols de 1 time: {sre.SCORING['oneTeamGoals']} pt (esperado {expected_scoring['oneTeamGoals']}) — {'OK' if sre.SCORING['oneTeamGoals']==expected_scoring['oneTeamGoals'] else 'DIVERGENTE'}</li>
              <li>Avanço correto: {sre.SCORING['advance']} pts (esperado {expected_scoring['advance']}) — {'OK' if sre.SCORING['advance']==expected_scoring['advance'] else 'DIVERGENTE'}</li>
              <li>Bônus campeão/vice/3º/4º: {sre.BONUS['champion']}/{sre.BONUS['runnerUp']}/{sre.BONUS['third']}/{sre.BONUS['fourth']} pts (esperado {expected_bonus['champion']}/{expected_bonus['runnerUp']}/{expected_bonus['third']}/{expected_bonus['fourth']}) — {'OK' if bonus_ok else 'DIVERGENTE'}</li>
              <li>Divisão do prêmio: {int(sre.PRIZES['first']*100)}% / {int(sre.PRIZES['second']*100)}% / {int(sre.PRIZES['third']*100)}% (esperado 70%/20%/10%, soma = {sum(expected_prizes.values())*100:.0f}%) — {'OK' if prizes_ok else 'DIVERGENTE'}</li></ul>
              Esta verificação existe porque uma auditoria anterior (julho de 2026, ver CHANGELOG v4.57) encontrou o pipeline de e-mail com valores de pontuação diferentes dos usados pelo site — o risco de "drift" silencioso entre as duas implementações é conhecido e monitorado desde então.""",
            "en": f"""Values used by the email pipeline (<code>send_result_email.py</code>) compared against expected values, declared independently in this audit script (not copied straight from <code>config.js</code>):
              <ul><li>Exact score: {sre.SCORING['exactScore']} pts (expected {expected_scoring['exactScore']}) — {'OK' if sre.SCORING['exactScore']==expected_scoring['exactScore'] else 'MISMATCH'}</li>
              <li>One team's goals: {sre.SCORING['oneTeamGoals']} pt (expected {expected_scoring['oneTeamGoals']}) — {'OK' if sre.SCORING['oneTeamGoals']==expected_scoring['oneTeamGoals'] else 'MISMATCH'}</li>
              <li>Correct advance: {sre.SCORING['advance']} pts (expected {expected_scoring['advance']}) — {'OK' if sre.SCORING['advance']==expected_scoring['advance'] else 'MISMATCH'}</li>
              <li>Champion/runner-up/3rd/4th bonus: {sre.BONUS['champion']}/{sre.BONUS['runnerUp']}/{sre.BONUS['third']}/{sre.BONUS['fourth']} pts (expected {expected_bonus['champion']}/{expected_bonus['runnerUp']}/{expected_bonus['third']}/{expected_bonus['fourth']}) — {'OK' if bonus_ok else 'MISMATCH'}</li>
              <li>Prize split: {int(sre.PRIZES['first']*100)}% / {int(sre.PRIZES['second']*100)}% / {int(sre.PRIZES['third']*100)}% (expected 70%/20%/10%, sums to {sum(expected_prizes.values())*100:.0f}%) — {'OK' if prizes_ok else 'MISMATCH'}</li></ul>
              This check exists because an earlier audit (July 2026, see CHANGELOG v4.57) found the email pipeline using different scoring values than the site itself — the risk of silent drift between the two implementations has been monitored ever since.""",
            "es": f"""Valores usados por el pipeline de correo (<code>send_result_email.py</code>) comparados contra los valores esperados, declarados de forma independiente en este script de auditoría (no copiados directamente de <code>config.js</code>):
              <ul><li>Marcador exacto: {sre.SCORING['exactScore']} pts (esperado {expected_scoring['exactScore']}) — {'OK' if sre.SCORING['exactScore']==expected_scoring['exactScore'] else 'DIVERGENTE'}</li>
              <li>Goles de 1 equipo: {sre.SCORING['oneTeamGoals']} pt (esperado {expected_scoring['oneTeamGoals']}) — {'OK' if sre.SCORING['oneTeamGoals']==expected_scoring['oneTeamGoals'] else 'DIVERGENTE'}</li>
              <li>Avance correcto: {sre.SCORING['advance']} pts (esperado {expected_scoring['advance']}) — {'OK' if sre.SCORING['advance']==expected_scoring['advance'] else 'DIVERGENTE'}</li>
              <li>Bono campeón/subcampeón/3º/4º: {sre.BONUS['champion']}/{sre.BONUS['runnerUp']}/{sre.BONUS['third']}/{sre.BONUS['fourth']} pts (esperado {expected_bonus['champion']}/{expected_bonus['runnerUp']}/{expected_bonus['third']}/{expected_bonus['fourth']}) — {'OK' if bonus_ok else 'DIVERGENTE'}</li>
              <li>División del premio: {int(sre.PRIZES['first']*100)}% / {int(sre.PRIZES['second']*100)}% / {int(sre.PRIZES['third']*100)}% (esperado 70%/20%/10%, suma {sum(expected_prizes.values())*100:.0f}%) — {'OK' if prizes_ok else 'DIVERGENTE'}</li></ul>
              Esta verificación existe porque una auditoría anterior (julio de 2026, ver CHANGELOG v4.57) encontró el pipeline de correo con valores de puntuación distintos a los del sitio — el riesgo de "drift" silencioso entre las dos implementaciones se monitorea desde entonces.""",
        },
    ))

    # B — Bracket structure integrity
    all_ids = set(sre.MATCH_TEAMS.keys())
    expected_count = 32
    slot_refs_ok = True
    bad_refs = []
    for mid, (a, b) in sre.MATCH_TEAMS.items():
        for raw in (a, b):
            m = re.match(r'^([WL])(\d+)$', str(raw))
            if m and m.group(2) not in all_ids:
                slot_refs_ok = False
                bad_refs.append(f"M{mid}: {raw}")
    bracket_ok = len(all_ids) == expected_count and slot_refs_ok
    findings.append(Finding(
        "bracket-integrity", "pass" if bracket_ok else "info",
        {"pt": "B. Integridade da estrutura do mata-mata", "en": "B. Bracket structure integrity", "es": "B. Integridad de la estructura de eliminación"},
        {
            "pt": f"""{expected_count} partidas do mata-mata cadastradas (esperado {expected_count}) — {'OK' if len(all_ids)==expected_count else 'DIVERGENTE'}. Todas as referências de vaga (ex.: "W101" = vencedor da partida 101, "L102" = perdedor da 102) apontam para partidas que realmente existem no bracket — {'OK, nenhuma referência quebrada' if slot_refs_ok else f'DIVERGENTE: {", ".join(bad_refs)}'}.""",
            "en": f"""{expected_count} knockout matches registered (expected {expected_count}) — {'OK' if len(all_ids)==expected_count else 'MISMATCH'}. Every slot reference (e.g. "W101" = winner of match 101, "L102" = loser of match 102) points to a match that actually exists in the bracket — {'OK, no broken references' if slot_refs_ok else f'MISMATCH: {", ".join(bad_refs)}'}.""",
            "es": f"""{expected_count} partidos de eliminación registrados (esperado {expected_count}) — {'OK' if len(all_ids)==expected_count else 'DIVERGENTE'}. Todas las referencias de cupo (ej.: "W101" = ganador del partido 101, "L102" = perdedor del 102) apuntan a partidos que realmente existen en el cuadro — {'OK, ninguna referencia rota' if slot_refs_ok else f'DIVERGENTE: {", ".join(bad_refs)}'}.""",
        },
    ))

    # C — Result data integrity (locked results: when goalsA != goalsB, the higher scorer must
    # be the recorded advanceSide. A tie is NOT a problem by itself — knockout matches can end
    # level after 90 minutes and go to penalties, which this state's goalsA/goalsB don't capture;
    # advanceSide is the source of truth for who actually advanced in that case.)
    result_problems = []
    for mid, r in sorted(locked_results.items(), key=lambda kv: int(kv[0])):
        gA, gB, side = r.get("goalsA"), r.get("goalsB"), r.get("advanceSide")
        if not (isinstance(gA, int) and isinstance(gB, int)) or side not in ("A", "B"):
            result_problems.append(f"M{mid}: goalsA={gA} goalsB={gB} advanceSide={side} (dados incompletos/inválidos)")
            continue
        if gA != gB:
            expected_side = "A" if gA > gB else "B"
            if side != expected_side:
                result_problems.append(f"M{mid}: goalsA={gA} goalsB={gB} advanceSide={side} (esperado {expected_side} pelo placar)")
    findings.append(Finding(
        "result-data-integrity", "pass" if not result_problems else "info",
        {"pt": "C. Integridade dos resultados travados", "en": "C. Locked result data integrity", "es": "C. Integridad de los resultados bloqueados"},
        {
            "pt": f"""{len(locked_results)} partidas travadas pelo admin, recontadas de forma independente: quando o placar tem um vencedor claro (gols diferentes), o lado marcado como <code>advanceSide</code> foi comparado contra o placar (<code>goalsA</code>/<code>goalsB</code>). Empates no tempo normal ({sum(1 for r in locked_results.values() if r.get('goalsA') == r.get('goalsB'))} desta rodada) são esperados em mata-mata — o time avança nos pênaltis, e <code>advanceSide</code> é a fonte da verdade nesse caso, já que o placar de pênaltis não é armazenado separadamente. {'Nenhuma inconsistência encontrada — em todas as ' + str(len(locked_results)) + ' partidas com dados completos, o lado vencedor bate com o placar registrado (ou o empate foi corretamente decidido nos pênaltis).' if not result_problems else 'Inconsistências: ' + '; '.join(result_problems)}""",
            "en": f"""{len(locked_results)} matches locked by the admin, independently recomputed: whenever the score has a clear winner (different goal counts), the side marked as <code>advanceSide</code> was checked against the score (<code>goalsA</code>/<code>goalsB</code>). Regulation-time draws ({sum(1 for r in locked_results.values() if r.get('goalsA') == r.get('goalsB'))} in this round) are expected in knockout football — the team advances on penalties, and <code>advanceSide</code> is the source of truth in that case, since the penalty shootout score isn't stored separately. {'No inconsistencies found — in all ' + str(len(locked_results)) + ' matches with complete data, the winning side matches the recorded score (or the draw was correctly decided on penalties).' if not result_problems else 'Inconsistencies: ' + '; '.join(result_problems)}""",
            "es": f"""{len(locked_results)} partidos bloqueados por el admin, recalculados de forma independiente: cuando el marcador tiene un ganador claro (goles distintos), el lado marcado como <code>advanceSide</code> se comparó contra el marcador (<code>goalsA</code>/<code>goalsB</code>). Los empates en tiempo reglamentario ({sum(1 for r in locked_results.values() if r.get('goalsA') == r.get('goalsB'))} en esta ronda) son esperados en fútbol de eliminación — el equipo avanza por penales, y <code>advanceSide</code> es la fuente de verdad en ese caso, ya que el marcador de penales no se almacena por separado. {'No se encontraron inconsistencias — en los ' + str(len(locked_results)) + ' partidos con datos completos, el lado ganador coincide con el marcador registrado (o el empate se decidió correctamente por penales).' if not result_problems else 'Inconsistencias: ' + '; '.join(result_problems)}""",
        },
    ))

    # D — Entry & payment data integrity
    all_ids_list = [e.get("id") for e in state.get("entries", [])]
    dup_ids = len(all_ids_list) != len(set(all_ids_list))
    orphan_picks = []
    for e in entries:
        for mid in (e.get("picks") or {}):
            if str(mid) not in sre.MATCH_TEAMS:
                orphan_picks.append(f"{e.get('entryName')}: M{mid}")
    paid_count = sum(1 for e in state.get("entries", []) if state.get("paid", {}).get(e.get("id")))
    data_ok = not dup_ids and not orphan_picks
    findings.append(Finding(
        "entry-data-integrity", "pass" if data_ok else "info",
        {"pt": "D. Integridade dos dados de participantes e pagamentos", "en": "D. Entry and payment data integrity", "es": "D. Integridad de los datos de participantes y pagos"},
        {
            "pt": f"""{len(state.get('entries', []))} entradas totais no banco, {len(deleted)} removidas (soft-delete), {demo_count} de demonstração, restando <b>{len(entries)} entradas reais válidas</b> para o ranking. IDs duplicados: {'nenhum — OK' if not dup_ids else 'ENCONTRADO(S) — DIVERGENTE'}. Palpites órfãos (referenciando uma partida que não existe no bracket): {'nenhum — OK' if not orphan_picks else 'ENCONTRADO(S): ' + '; '.join(orphan_picks)}. {paid_count} de {len(state.get('entries', []))} entradas marcadas como pagas.""",
            "en": f"""{len(state.get('entries', []))} total entries in the database, {len(deleted)} soft-deleted, {demo_count} demo entries, leaving <b>{len(entries)} valid real entries</b> for the ranking. Duplicate IDs: {'none — OK' if not dup_ids else 'FOUND — MISMATCH'}. Orphan picks (referencing a match that doesn't exist in the bracket): {'none — OK' if not orphan_picks else 'FOUND: ' + '; '.join(orphan_picks)}. {paid_count} of {len(state.get('entries', []))} entries marked as paid.""",
            "es": f"""{len(state.get('entries', []))} entradas totales en la base de datos, {len(deleted)} eliminadas (soft-delete), {demo_count} de demostración, quedando <b>{len(entries)} entradas reales válidas</b> para el ranking. IDs duplicados: {'ninguno — OK' if not dup_ids else 'ENCONTRADO(S) — DIVERGENTE'}. Pronósticos huérfanos (referenciando un partido que no existe en el cuadro): {'ninguno — OK' if not orphan_picks else 'ENCONTRADO(S): ' + '; '.join(orphan_picks)}. {paid_count} de {len(state.get('entries', []))} entradas marcadas como pagadas.""",
        },
    ))

    # E — Independent score recomputation, per real entry
    mismatches = []
    rows = []
    for e in entries:
        official = sre.score_entry_total(e, locked_results)
        indep = independent_entry_total(e, locked_results)
        match = official == indep
        if not match:
            mismatches.append(e.get("entryName"))
        rows.append((e.get("entryName", "?"), official, indep, match))
    rows.sort(key=lambda r: -r[1])

    def score_table(lang):
        h_name = {"pt": "Entrada", "en": "Entry", "es": "Entrada"}[lang]
        h_off = {"pt": "Pontos (oficial)", "en": "Points (official)", "es": "Puntos (oficial)"}[lang]
        h_ind = {"pt": "Pontos (recálculo independente)", "en": "Points (independent recompute)", "es": "Puntos (recálculo independiente)"}[lang]
        h_status = {"pt": "Confere?", "en": "Match?", "es": "¿Coincide?"}[lang]
        ok_txt = {"pt": "✓ sim", "en": "✓ yes", "es": "✓ sí"}[lang]
        bad_txt = {"pt": "✗ NÃO", "en": "✗ NO", "es": "✗ NO"}[lang]
        body = "".join(
            f"<tr class=\"{'row-bad' if not m else ''}\"><td>{esc(n)}</td><td class=\"num\">{o}</td><td class=\"num\">{i}</td><td>{ok_txt if m else bad_txt}</td></tr>"
            for n, o, i, m in rows
        )
        return f"<table class='audit-table'><thead><tr><th>{h_name}</th><th>{h_off}</th><th>{h_ind}</th><th>{h_status}</th></tr></thead><tbody>{body}</tbody></table>"

    findings.append(Finding(
        "independent-recompute", "pass" if not mismatches else "info",
        {"pt": "E. Recálculo independente da pontuação — todas as entradas reais", "en": "E. Independent score recomputation — all real entries", "es": "E. Recálculo independiente de puntuación — todas las entradas reales"},
        {
            "pt": f"""Para cada uma das {len(entries)} entradas reais, a pontuação foi recalculada do zero (bracket + palpites + resultados brutos), em código separado do site e do pipeline de e-mail, e comparada contra o valor "oficial" produzido por <code>score_entry_total()</code>. {'<b>Resultado: as ' + str(len(entries)) + ' entradas conferem exatamente — nenhuma divergência encontrada.</b>' if not mismatches else '<b>DIVERGÊNCIAS ENCONTRADAS em: ' + ', '.join(mismatches) + '</b>'}<br><br>{score_table('pt')}""",
            "en": f"""For each of the {len(entries)} real entries, the score was recomputed from scratch (bracket + picks + raw results), in code kept separate from the site and the email pipeline, and compared against the "official" value produced by <code>score_entry_total()</code>. {'<b>Result: all ' + str(len(entries)) + ' entries match exactly — no discrepancies found.</b>' if not mismatches else '<b>DISCREPANCIES FOUND in: ' + ', '.join(mismatches) + '</b>'}<br><br>{score_table('en')}""",
            "es": f"""Para cada una de las {len(entries)} entradas reales, la puntuación se recalculó desde cero (cuadro + pronósticos + resultados brutos), en código separado del sitio y del pipeline de correo, y se comparó contra el valor "oficial" producido por <code>score_entry_total()</code>. {'<b>Resultado: las ' + str(len(entries)) + ' entradas coinciden exactamente — no se encontraron discrepancias.</b>' if not mismatches else '<b>DISCREPANCIAS ENCONTRADAS en: ' + ', '.join(mismatches) + '</b>'}<br><br>{score_table('es')}""",
        },
    ))

    # F — Ranking & tiebreak verification
    ranked = sorted(entries, key=lambda e: (
        -sre.score_entry_total(e, locked_results),
        -sre.exact_match_count(e, locked_results),
        -sre.podium_hits(e, locked_results),
    ))
    indep_ranked_keys = [(e.get("id"), independent_entry_total(e, locked_results), independent_exact_count(e, locked_results)) for e in entries]
    official_ranked_keys = [(e.get("id"), sre.score_entry_total(e, locked_results), sre.exact_match_count(e, locked_results)) for e in entries]
    indep_order = sorted(indep_ranked_keys, key=lambda k: (-k[1], -k[2]))
    official_order = sorted(official_ranked_keys, key=lambda k: (-k[1], -k[2]))
    order_match = [k[0] for k in indep_order] == [k[0] for k in official_order]
    top3 = ranked[:3]
    findings.append(Finding(
        "ranking-tiebreak", "pass" if order_match else "info",
        {"pt": "F. Verificação do ranking e critérios de desempate", "en": "F. Ranking and tiebreak verification", "es": "F. Verificación del ranking y criterios de desempate"},
        {
            "pt": f"""Critério de desempate documentado: total de pontos → nº de placares exatos → acertos de pódio (campeão/vice/3º). A ordem de classificação produzida pelo recálculo independente foi comparada contra a ordem oficial — {'OK, ordens idênticas.' if order_match else 'DIVERGENTE — as ordens não batem.'} Top 3 provisório atual (antes da Final): {', '.join(f'{i+1}º {e.get("entryName")} ({sre.score_entry_total(e, locked_results)} pts)' for i, e in enumerate(top3))}. <i>Este ranking ainda é provisório — M104 (Final) decide o pódio final e os prêmios.</i>""",
            "en": f"""Documented tiebreak rule: total points → number of exact scores → podium hits (champion/runner-up/3rd). The ranking order produced by the independent recompute was compared against the official order — {'OK, identical order.' if order_match else 'MISMATCH — orders do not agree.'} Current provisional top 3 (before the Final): {', '.join(f'{i+1} {e.get("entryName")} ({sre.score_entry_total(e, locked_results)} pts)' for i, e in enumerate(top3))}. <i>This ranking is still provisional — M104 (the Final) decides the final podium and prizes.</i>""",
            "es": f"""Criterio de desempate documentado: total de puntos → nº de marcadores exactos → aciertos de podio (campeón/subcampeón/3º). El orden de clasificación producido por el recálculo independiente se comparó contra el orden oficial — {'OK, órdenes idénticos.' if order_match else 'DIVERGENTE — los órdenes no coinciden.'} Top 3 provisional actual (antes de la Final): {', '.join(f'{i+1}º {e.get("entryName")} ({sre.score_entry_total(e, locked_results)} pts)' for i, e in enumerate(top3))}. <i>Este ranking sigue siendo provisional — M104 (la Final) decide el podio final y los premios.</i>""",
        },
    ))

    # G — Prize/pot mechanism verification
    pot = paid_count * sre.ENTRY_FEE
    payouts_info = sre.compute_final_payouts(state, locked_results)
    tournament_decided = payouts_info is not None
    findings.append(Finding(
        "prize-mechanism", "pass",
        {"pt": "G. Verificação do mecanismo de premiação", "en": "G. Prize mechanism verification", "es": "G. Verificación del mecanismo de premiación"},
        {
            "pt": f"""Pote atual: {paid_count} entradas pagas × ${sre.ENTRY_FEE} = <b>${pot}</b>. Divisão: 70% / 20% / 10% para 1º / 2º / 3º lugar do ranking geral (por pontos), com empates reais divididos proporcionalmente entre os empatados (regra já documentada na aba Regras do site). {'O torneio ainda não está decidido (M103 e/ou M104 pendentes) — o pódio final e os valores exatos de premiação serão calculados automaticamente assim que a Final terminar e for travada pelo admin.' if not tournament_decided else 'Torneio decidido — pódio final: ' + ', '.join(f'{p["rank"]}º {p["entryName"]} (${p["amount"]:.2f})' for p in payouts_info["payouts"])}""",
            "en": f"""Current pot: {paid_count} paid entries × ${sre.ENTRY_FEE} = <b>${pot}</b>. Split: 70% / 20% / 10% for 1st / 2nd / 3rd place in the overall points ranking, with genuine ties split proportionally among tied entries (rule already documented in the site's own Rules tab). {'The tournament is not yet decided (M103 and/or M104 still pending) — the final podium and exact prize amounts will be computed automatically once the Final concludes and is locked by the admin.' if not tournament_decided else 'Tournament decided — final podium: ' + ', '.join(f'{p["rank"]} {p["entryName"]} (${p["amount"]:.2f})' for p in payouts_info["payouts"])}""",
            "es": f"""Bolsa actual: {paid_count} entradas pagadas × ${sre.ENTRY_FEE} = <b>${pot}</b>. División: 70% / 20% / 10% para 1º / 2º / 3º lugar del ranking general (por puntos), con empates reales divididos proporcionalmente entre los empatados (regla ya documentada en la pestaña Reglas del sitio). {'El torneo aún no está decidido (M103 y/o M104 pendientes) — el podio final y los montos exactos de premiación se calcularán automáticamente en cuanto termine la Final y sea bloqueada por el admin.' if not tournament_decided else 'Torneo decidido — podio final: ' + ', '.join(f'{p["rank"]}º {p["entryName"]} (${p["amount"]:.2f})' for p in payouts_info["payouts"])}""",
        },
    ))

    # H — Findings identified and remediated during this audit period
    findings.append(Finding(
        "remediated-issues", "remediated",
        {"pt": "H. Achados identificados e corrigidos durante o período de auditoria", "en": "H. Findings identified and remediated during the audit period", "es": "H. Hallazgos identificados y corregidos durante el período de auditoría"},
        {
            "pt": """Três problemas foram identificados e corrigidos nos dias 18–19/07/2026, antes da publicação deste relatório:
              <ol>
              <li><b>Prévia ao vivo sem bônus de pódio (v4.147).</b> A tabela "Pontos (provisório)" exibida durante uma partida ao vivo não incluía o bônus de campeão/vice/3º/4º para M103 e M104, mesmo quando o palpite de avanço já era o vencedor no placar ao vivo. Não afetava a pontuação oficial nem os pagamentos — apenas a prévia exibida durante a partida. Corrigido no mesmo dia.</li>
              <li><b>Prévia ao vivo comparando lado do bracket em vez de time real (v4.149).</b> A correção acima comparava apenas o lado (A/B) escolhido no palpite contra o lado vencedor ao vivo — não o TIME que o próprio bracket da entrada efetivamente previa para aquela posição. Testado com dados reais de produção: das 21 entradas que escolheram o lado B do M103, apenas 2 (Simone Hirle #4, Gabriel Ferrari) haviam de fato previsto "Inglaterra" ao rastrear o próprio bracket — as outras 19 previram times completamente diferentes que só coincidiam no mesmo lado. As 21 exibiam o bônus incorretamente na prévia ao vivo. <b>Importante: a pontuação OFICIAL (<code>scoreEntry()</code>/<code>score_entry_total()</code>) sempre comparou pelo nome do time, nunca pelo lado — nunca esteve incorreta, e nenhum participante foi pontuado ou pago de forma errada em nenhum momento.</b> Corrigido no mesmo dia, verificado com os mesmos dados reais.</li>
              <li><b>Bônus do 3º lugar retido até a Final também estar decidida (v4.151) — este SIM afetava a pontuação oficial.</b> Ao contrário dos dois itens acima, este afetava <code>scoreEntry()</code>/<code>score_entry_total()</code> diretamente: a função que calcula o pódio real (<code>podiumFromResults()</code>/<code>_podium_from_results()</code>) só retornava um resultado quando M103 <b>e</b> M104 estavam AMBOS decididos — mesmo o M103 já estando totalmente resolvido (Inglaterra 3º lugar, confirmado em 19/07). Isso zerou o bônus de 3º/4º lugar de todo mundo, incluindo as 2 entradas que realmente previram a Inglaterra (Simone Hirle #4, Gabriel Ferrari) — cada uma perdendo 10 pts na exibição do ranking e no e-mail enviado logo após o M103. Corrigido para que campeão/vice (M104) e 3º/4º lugar (M103) sejam calculados de forma independente, cada um assim que sua respectiva partida trava. O ranking do site já reflete o valor correto automaticamente (não é armazenado, é recalculado a cada carregamento); o e-mail que já foi enviado após o M103 permanece com o valor antigo (sem o bônus) — o próximo e-mail (após a Final) mostrará o total já correto para todos.</li>
              </ol>
              As três correções foram publicadas e verificadas antes deste relatório ser gerado — ver <code>bolao/CHANGELOG.md</code> v4.147–v4.151 para o histórico completo.""",
            "en": """Three issues were identified and fixed on 2026-07-18/19, before this report was published:
              <ol>
              <li><b>Live preview missing podium bonus (v4.147).</b> The "Points (provisional)" table shown during a live match did not include the champion/runner-up/3rd/4th bonus for M103 and M104, even when the advance pick was already the leading side in the live score. Did not affect official scoring or payouts — only the preview shown during the match. Fixed the same day.</li>
              <li><b>Live preview comparing bracket side instead of the real team (v4.149).</b> The fix above only compared the bracket side (A/B) chosen in a pick against the currently-leading side — not which TEAM the entry's own bracket picks actually predicted for that slot. Tested against real production data: of 21 entries that picked side B for M103, only 2 (Simone Hirle #4, Gabriel Ferrari) had actually predicted "England" specifically by tracing their own bracket — the other 19 predicted entirely different teams that just happened to land on the same side. All 21 wrongly showed the bonus in the live preview. <b>Important: OFFICIAL scoring (<code>scoreEntry()</code>/<code>score_entry_total()</code>) always compared by team name, never by side — it was never incorrect, and no participant was ever scored or paid incorrectly at any point.</b> Fixed the same day, verified against the same real data.</li>
              <li><b>3rd-place bonus withheld until the Final was also decided (v4.151) — this one DID affect official scoring.</b> Unlike the two items above, this one hit <code>scoreEntry()</code>/<code>score_entry_total()</code> directly: the function that computes the real podium (<code>podiumFromResults()</code>/<code>_podium_from_results()</code>) only returned a result once BOTH M103 and M104 were decided — even though M103 was already fully resolved (England 3rd, confirmed 2026-07-19). This zeroed out the 3rd/4th place bonus for everyone, including the 2 entries who had actually predicted England (Simone Hirle #4, Gabriel Ferrari) — each missing 10 pts in the ranking display and in the email sent right after M103. Fixed so champion/runner-up (M104) and 3rd/4th place (M103) are computed independently, each as soon as its own match locks. The site's ranking already reflects the correct value automatically (it's recomputed on every load, never cached); the email already sent after M103 keeps the old value (no bonus) — the next email (after the Final) will show the correct total for everyone.</li>
              </ol>
              All three fixes were shipped and verified before this report was generated — see <code>bolao/CHANGELOG.md</code> v4.147–v4.151 for the full history.""",
            "es": """Se identificaron y corrigieron tres problemas el 18–19/07/2026, antes de la publicación de este informe:
              <ol>
              <li><b>Vista previa en vivo sin bono de podio (v4.147).</b> La tabla "Puntos (provisorio)" mostrada durante un partido en vivo no incluía el bono de campeón/subcampeón/3º/4º para M103 y M104, incluso cuando el pronóstico de avance ya era el lado que iba ganando en el marcador en vivo. No afectaba la puntuación oficial ni los pagos — solo la vista previa mostrada durante el partido. Corregido el mismo día.</li>
              <li><b>Vista previa en vivo comparando el lado del cuadro en vez del equipo real (v4.149).</b> La corrección anterior solo comparaba el lado (A/B) elegido en el pronóstico contra el lado que iba ganando en vivo — no el EQUIPO que el propio cuadro de la entrada realmente predecía para esa posición. Probado con datos reales de producción: de las 21 entradas que eligieron el lado B del M103, solo 2 (Simone Hirle #4, Gabriel Ferrari) habían predicho realmente "Inglaterra" al rastrear su propio cuadro — las otras 19 predijeron equipos completamente distintos que solo coincidían en el mismo lado. Las 21 mostraban el bono incorrectamente en la vista previa en vivo. <b>Importante: la puntuación OFICIAL (<code>scoreEntry()</code>/<code>score_entry_total()</code>) siempre comparó por nombre del equipo, nunca por lado — nunca estuvo incorrecta, y ningún participante fue puntuado o pagado de forma errónea en ningún momento.</b> Corregido el mismo día, verificado con los mismos datos reales.</li>
              <li><b>Bono de 3er lugar retenido hasta que la Final también estuviera decidida (v4.151) — este SÍ afectaba la puntuación oficial.</b> A diferencia de los dos anteriores, este afectaba directamente <code>scoreEntry()</code>/<code>score_entry_total()</code>: la función que calcula el podio real (<code>podiumFromResults()</code>/<code>_podium_from_results()</code>) solo devolvía un resultado cuando M103 Y M104 estaban AMBOS decididos — aunque M103 ya estaba totalmente resuelto (Inglaterra 3º lugar, confirmado el 19/07). Esto anuló el bono de 3º/4º lugar de todos, incluidas las 2 entradas que realmente predijeron Inglaterra (Simone Hirle #4, Gabriel Ferrari) — cada una perdiendo 10 pts en el ranking mostrado y en el correo enviado justo después del M103. Corregido para que campeón/subcampeón (M104) y 3º/4º lugar (M103) se calculen de forma independiente, cada uno en cuanto se bloquea su propio partido. El ranking del sitio ya refleja el valor correcto automáticamente (se recalcula en cada carga, nunca se almacena); el correo ya enviado después del M103 mantiene el valor anterior (sin el bono) — el próximo correo (después de la Final) mostrará el total correcto para todos.</li>
              </ol>
              Las tres correcciones se publicaron y verificaron antes de generar este informe — ver <code>bolao/CHANGELOG.md</code> v4.147–v4.151 para el historial completo.""",
        },
    ))

    # I — Static self-test suite
    static_ok, static_results = audit_scoring.run_static_audit(sre, verbose=False)

    def static_list(lang):
        return "<ul>" + "".join(f"<li>{'✓' if ok else '✗'} {esc(name)}{'' if ok else ' — ' + esc(detail)}</li>" for name, ok, detail in static_results) + "</ul>"

    findings.append(Finding(
        "static-suite", "pass" if static_ok else "info",
        {"pt": "I. Suíte de autoteste estática (audit_scoring.py)", "en": "I. Static self-test suite (audit_scoring.py)", "es": "I. Suite de autopruebas estática (audit_scoring.py)"},
        {
            "pt": f"""Suíte de testes que roda automaticamente antes de qualquer envio de e-mail (<code>send_result_email.py --auto</code> se recusa a rodar se esta suíte falhar). {static_list('pt')}""",
            "en": f"""Test suite that runs automatically before any email send (<code>send_result_email.py --auto</code> refuses to run if this suite fails). {static_list('en')}""",
            "es": f"""Suite de pruebas que se ejecuta automáticamente antes de cualquier envío de correo (<code>send_result_email.py --auto</code> se niega a ejecutarse si esta suite falla). {static_list('es')}""",
        },
    ))

    meta = {
        "generated_at": datetime.now(timezone.utc),
        "entry_count": len(entries),
        "locked_count": len(locked_results),
        "pot": pot,
        "tournament_decided": tournament_decided,
        "all_pass": not mismatches and data_ok and bracket_ok and not result_problems and order_match and static_ok,
    }
    return findings, meta


# ── Full per-pick traceability (detail page) ───────────────────────────────────────────────────

def compute_picks_traceability(state, results):
    """Every real entry × every one of the 32 knockout matches: pick, real result, points
    earned (base + podium bonus, matching the same per-match itemization shipped in v4.152),
    sorted by current official total. This is the raw material for "audit every single result of
    every single game in every single person's pick" (Eduardo, 2026-07-19)."""
    deleted = set(state.get("deletedIds", []))
    entries = [e for e in state.get("entries", [])
               if e.get("id") not in deleted and not (e.get("diagnostics") or {}).get("demo")]
    out = []
    for e in entries:
        rows = []
        for mid in sorted(sre.MATCH_TEAMS.keys(), key=int):
            pick = (e.get("picks") or {}).get(mid)
            result = results.get(mid)
            tA, tB = sre._real_teams(mid, results)
            pts, note = 0, "—"
            if pick and result:
                pts, note, _ = sre.score_match(pick, result, teamA=tA, teamB=tB, mid=mid)
                bonus_pts, bonus_note, _ = sre.match_podium_bonus_note(e, mid, results)
                if bonus_pts:
                    pts += bonus_pts
                    note = f"{note}, {bonus_note}" if note != "—" else bonus_note
            def _fmt(p, side_field="advanceSide"):
                if not p:
                    return "—"
                team = tB if p.get(side_field) == "B" else tA
                return f'{p.get("goalsA")}–{p.get("goalsB")} ({team})'
            rows.append({
                "mid": mid, "phase": _phase_for_mid(mid), "teamA": tA, "teamB": tB,
                "pick": _fmt(pick), "result": _fmt(result) if result else "—",
                "pts": pts, "note": note,
            })
        out.append({
            "name": e.get("entryName", "?"), "id": e.get("id"),
            "total": sre.score_entry_total(e, results), "rows": rows,
        })
    out.sort(key=lambda x: -x["total"])
    return out


def render_picks_detail(traceability, meta):
    idx_links = "".join(
        f'<a href="#entry-{i}">{i+1}. {esc(item["name"])} ({item["total"]} pts)</a><br>'
        for i, item in enumerate(traceability)
    )
    blocks = []
    for i, item in enumerate(traceability):
        rows_html = "".join(
            f'<tr><td>M{esc(r["mid"])}</td><td>{esc(PHASE_LABELS[r["phase"]]["pt"])}</td>'
            f'<td>{esc(r["teamA"])}</td><td>{esc(r["teamB"])}</td>'
            f'<td>{esc(r["pick"])}</td><td>{esc(r["result"])}</td>'
            f'<td class="num">{r["pts"]}</td><td>{esc(r["note"])}</td></tr>'
            for r in item["rows"]
        )
        blocks.append(f"""<details class="entry-block" id="entry-{i}">
  <summary>{i+1}. {esc(item['name'])} <span class="entry-badge">{item['total']} pts</span></summary>
  <div class="entry-body">
    <div class="table-scroll">
    <table class="detail-table">
      <thead><tr><th>Partida</th><th>Fase</th><th>Time A</th><th>Time B</th><th>Palpite</th><th>Resultado real</th><th>Pts</th><th>Detalhe</th></tr></thead>
      <tbody>{rows_html}</tbody>
    </table>
    </div>
  </div>
</details>""")

    now = meta["generated_at"]
    ts = now.strftime("%d/%m/%Y %H:%M UTC")
    return f"""<!doctype html>
<html lang="pt-BR">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex,nofollow">
<title>Auditoria Detalhada — Palpites e Pontuação — Bolão do Ferrari</title>
<style>{DETAIL_PAGE_STYLE}
[data-lang] {{ display:none; }} [data-lang].lang-active {{ display:block; }}
</style>
</head>
<body>
<div class="doc">
  <div class="lang-bar">
    <a class="backlink" href="audit-report.html">← Resumo executivo / Executive summary</a>
    <button data-setlang="pt" class="active">🇧🇷 Português</button>
    <button data-setlang="en">🇺🇸 English</button>
    <button data-setlang="es">🇲🇽 Español</button>
  </div>
  <div data-lang="pt" class="lang-active">
    <div class="page-header">
      <h1>🔍 Auditoria Detalhada — Cada Palpite, Cada Partida, Cada Ponto</h1>
      <p><b>Gerado em:</b> {ts} · <b>Entradas:</b> {len(traceability)} · <b>Partidas por entrada:</b> 32</p>
      <p>Esta página lista, para cada uma das {len(traceability)} entradas reais do bolão, o palpite dado e o resultado real de todas as 32 partidas do mata-mata, com a pontuação exata ganha em cada uma (incluindo o bônus de pódio, quando aplicável). Clique no nome de uma entrada para expandir os detalhes.</p>
      <p style="font-size:12px;color:#6b7280">Nota: os detalhes por partida (coluna "Detalhe") são mostrados em português para manter esta página gerenciável — os nomes dos times e os números de pontos são iguais em qualquer idioma. O <a href="audit-report.html">resumo executivo</a> está disponível nas 3 línguas.</p>
    </div>
    <div class="entry-block" style="padding:14px 18px"><b>Índice</b><div class="idx-list" style="margin-top:8px">{idx_links}</div></div>
    {"".join(blocks)}
  </div>
  <div data-lang="en">
    <div class="page-header">
      <h1>🔍 Detailed Audit — Every Pick, Every Match, Every Point</h1>
      <p><b>Generated at:</b> {ts} · <b>Entries:</b> {len(traceability)} · <b>Matches per entry:</b> 32</p>
      <p>This page lists, for each of the {len(traceability)} real bolão entries, the pick made and the real result for all 32 knockout matches, with the exact points earned on each (including the podium bonus, when applicable). Click an entry's name to expand its details.</p>
      <p style="font-size:12px;color:#6b7280">Note: per-match details (the "Detalhe" column) are shown in Portuguese to keep this page manageable — team names and point numbers are the same in any language. The <a href="audit-report.html">executive summary</a> is available in all 3 languages.</p>
    </div>
    <div class="entry-block" style="padding:14px 18px"><b>Index</b><div class="idx-list" style="margin-top:8px">{idx_links}</div></div>
    {"".join(blocks)}
  </div>
  <div data-lang="es">
    <div class="page-header">
      <h1>🔍 Auditoría Detallada — Cada Pronóstico, Cada Partido, Cada Punto</h1>
      <p><b>Generado el:</b> {ts} · <b>Entradas:</b> {len(traceability)} · <b>Partidos por entrada:</b> 32</p>
      <p>Esta página lista, para cada una de las {len(traceability)} entradas reales del bolão, el pronóstico dado y el resultado real de los 32 partidos de eliminación, con la puntuación exacta obtenida en cada uno (incluyendo el bono de podio, cuando aplica). Haz clic en el nombre de una entrada para expandir los detalles.</p>
      <p style="font-size:12px;color:#6b7280">Nota: los detalles por partido (columna "Detalhe") se muestran en portugués para mantener esta página manejable — los nombres de los equipos y los números de puntos son iguales en cualquier idioma. El <a href="audit-report.html">resumen ejecutivo</a> está disponible en los 3 idiomas.</p>
    </div>
    <div class="entry-block" style="padding:14px 18px"><b>Índice</b><div class="idx-list" style="margin-top:8px">{idx_links}</div></div>
    {"".join(blocks)}
  </div>
</div>
<script>{DETAIL_PAGE_SCRIPT}</script>
</body>
</html>"""


# ── Governance / edit-trail traceability (detail page) ─────────────────────────────────────────

def compute_governance_trail(state):
    """createdAt/updatedAt per entry, plus the real auditLog (before/after pick changes, IP,
    device) already captured by the site's own "editar por código" flow. Flags entries whose
    updatedAt differs from createdAt but have NO matching auditLog record as an anomaly to
    disclose, rather than silently presenting them as verified participant edits — see
    CONSISTENCY_MATRIX.md for why (predates this audit, cause not established)."""
    deleted = set(state.get("deletedIds", []))
    entries = [e for e in state.get("entries", [])
               if e.get("id") not in deleted and not (e.get("diagnostics") or {}).get("demo")]
    audit_log = state.get("auditLog") or []
    by_entry_id = {}
    for rec in audit_log:
        by_entry_id.setdefault(rec.get("entryId"), []).append(rec)

    rows, anomalies = [], []
    for e in entries:
        created, updated = e.get("createdAt"), e.get("updatedAt")
        modified = bool(updated and updated != created)
        records = sorted(by_entry_id.get(e.get("id"), []), key=lambda r: r.get("ts", ""))
        real_changes = [r for r in records if r.get("changeCount", 0) > 0]
        if modified and not records:
            anomalies.append(e.get("entryName", "?"))
        rows.append({
            "name": e.get("entryName", "?"), "created": created, "updated": updated,
            "modified": modified, "records": records, "hasRealChanges": bool(real_changes),
        })
    rows.sort(key=lambda r: (not r["modified"], r["name"]))
    return {"rows": rows, "anomalies": anomalies, "totalAuditLogRecords": len(audit_log)}


def render_governance_detail(gov, meta):
    def fmt_ts(ts):
        if not ts:
            return "—"
        try:
            return datetime.fromisoformat(ts.replace("Z", "+00:00")).strftime("%d/%m/%Y %H:%M UTC")
        except ValueError:
            return ts

    rows_html = []
    for r in gov["rows"]:
        badge = ('<span class="entry-badge">criada apenas</span>' if not r["modified"]
                  else '<span class="entry-badge warn">modificada, sem registro</span>' if not r["records"]
                  else f'<span class="entry-badge">{len(r["records"])} evento(s) registrado(s)</span>')
        records_html = ""
        if r["records"]:
            recs = []
            for rec in r["records"]:
                changes = rec.get("changes") or []
                if changes:
                    ch_rows = "".join(
                        f'<tr><td>M{esc(c.get("match"))}</td>'
                        f'<td>{esc(c["before"].get("goalsA"))}–{esc(c["before"].get("goalsB"))} ({esc(c["before"].get("advanceSide"))})</td>'
                        f'<td>{esc(c["after"].get("goalsA"))}–{esc(c["after"].get("goalsB"))} ({esc(c["after"].get("advanceSide"))})</td></tr>'
                        for c in changes if c.get("before") and c.get("after")
                    )
                    ch_table = f'<div class="table-scroll"><table class="detail-table"><thead><tr><th>Partida</th><th>Antes</th><th>Depois</th></tr></thead><tbody>{ch_rows}</tbody></table></div>' if ch_rows else "<p style='font-size:12px;color:#6b7280'>Sem mudança de palpite neste evento (outro campo alterado).</p>"
                else:
                    ch_table = "<p style='font-size:12px;color:#6b7280'>Sem mudanças registradas neste evento.</p>"
                recs.append(f"""<div style="margin:10px 0;padding:10px 12px;background:#f8fafc;border-radius:8px;font-size:12.5px">
                  <b>{fmt_ts(rec.get('ts'))}</b> · {rec.get('changeCount', 0)} mudança(s) · IP {esc(rec.get('ip', '—') or '—')} · {esc(rec.get('platform', '—') or '—')} · tela {esc(rec.get('screen', '—') or '—')} · idioma do navegador {esc(rec.get('lang', '—') or '—')}
                  {ch_table}
                </div>""")
            records_html = "".join(recs)
        rows_html.append(f"""<details class="entry-block">
  <summary>{esc(r['name'])} {badge}</summary>
  <div class="entry-body">
    <p style="font-size:13px"><b>Criada em:</b> {fmt_ts(r['created'])} &nbsp;·&nbsp; <b>Última atualização:</b> {fmt_ts(r['updated'])}</p>
    {records_html}
  </div>
</details>""")

    anomaly_html = ""
    if gov["anomalies"]:
        names = ", ".join(esc(n) for n in gov["anomalies"])
        anomaly_html = f"""<div class="anomaly-box">
          <b>⚠ Achado a divulgar:</b> {len(gov['anomalies'])} entrada(s) têm <code class="small">updatedAt</code> diferente de
          <code class="small">createdAt</code> mas SEM um registro correspondente no log de auditoria: {names}.
          Isso não corresponde a uma edição feita pela função "editar por código" do site (que sempre grava um registro) —
          provavelmente reflete uma operação administrativa ou de migração de dados anterior a esta auditoria, cuja causa
          exata não foi estabelecida. Nenhuma mudança de palpite foi registrada para essas entradas; o valor de
          <code class="small">updatedAt</code> por si só não deve ser interpretado como "o participante alterou os palpites".
        </div>"""

    now = meta["generated_at"]
    ts_now = now.strftime("%d/%m/%Y %H:%M UTC")
    modified_count = sum(1 for r in gov["rows"] if r["modified"])
    return f"""<!doctype html>
<html lang="pt-BR">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex,nofollow">
<title>Auditoria Detalhada — Governança e Histórico de Edições — Bolão do Ferrari</title>
<style>{DETAIL_PAGE_STYLE}</style>
</head>
<body>
<div class="doc">
  <div class="lang-bar">
    <a class="backlink" href="audit-report.html">← Resumo executivo / Executive summary</a>
  </div>
  <div class="page-header">
    <h1>📋 Auditoria Detalhada — Governança e Histórico de Edições</h1>
    <p><b>Gerado em:</b> {ts_now} · <b>Entradas:</b> {len(gov['rows'])} · <b>Modificadas:</b> {modified_count} · <b>Eventos no log de auditoria:</b> {gov['totalAuditLogRecords']}</p>
    <p>Data/hora de criação (<code class="small">createdAt</code>) e da última atualização (<code class="small">updatedAt</code>) de cada entrada, mais o histórico completo de edições feitas pela função "editar por código" do site — com o valor antes/depois de cada palpite alterado, endereço IP completo, dispositivo, tamanho de tela e idioma do navegador, exatamente como capturado pelo próprio site no momento da edição. E-mails de participantes não são exibidos nesta página, seguindo a mesma política de privacidade já aplicada no restante do site (aba Participantes é restrita ao admin).</p>
  </div>
  {anomaly_html}
  {"".join(rows_html)}
</div>
</body>
</html>"""


# ── HTML rendering ──────────────────────────────────────────────────────────────────────────

STATUS_LABEL = {
    "pass":       {"pt": "✓ SEM EXCEÇÕES", "en": "✓ NO EXCEPTIONS", "es": "✓ SIN EXCEPCIONES"},
    "remediated": {"pt": "⚠ CORRIGIDO",     "en": "⚠ REMEDIATED",   "es": "⚠ CORREGIDO"},
    "info":       {"pt": "ℹ INFORMATIVO",   "en": "ℹ INFORMATIONAL","es": "ℹ INFORMATIVO"},
}


def render_report(findings, meta, state):
    now = meta["generated_at"]
    ts_pt = now.strftime("%d/%m/%Y %H:%M UTC")
    ts_en = now.strftime("%B %d, %Y %H:%M UTC")
    ts_es = now.strftime("%d/%m/%Y %H:%M UTC")

    def sections_html(lang):
        out = []
        for f in findings:
            badge = STATUS_LABEL[f.status][lang]
            badge_class = f"badge-{f.status}"
            out.append(f"""<section class="audit-section">
              <h2>{esc(f.title[lang])} <span class="badge {badge_class}">{badge}</span></h2>
              <div class="section-body">{f.detail[lang]}</div>
            </section>""")
        return "\n".join(out)

    opinion = {
        "pt": "sem exceções não corrigidas" if meta["all_pass"] else "com itens a revisar",
        "en": "with no unremediated exceptions" if meta["all_pass"] else "with items to review",
        "es": "sin excepciones sin corregir" if meta["all_pass"] else "con puntos a revisar",
    }

    header_pt = f"""
    <header class="audit-header">
      <div class="audit-kicker">Bolão do Ferrari · Auditoria Técnica Independente Automatizada</div>
      <h1>Relatório de Auditoria — Integridade de Pontuação e Premiação</h1>
      <div class="audit-meta">
        <div><b>Escopo:</b> Copa do Mundo 2026 — pontuação, ranking e mecanismo de premiação</div>
        <div><b>Data/hora de geração:</b> {ts_pt}</div>
        <div><b>Entradas reais auditadas:</b> {meta['entry_count']}</div>
        <div><b>Partidas travadas auditadas:</b> {meta['locked_count']} de 32</div>
        <div><b>Pote atual:</b> ${meta['pot']}</div>
        <div><b>Opinião:</b> {opinion['pt']}</div>
      </div>
      <p class="audit-disclaimer">Este relatório é gerado por um sistema de verificação automatizada próprio do Bolão do Ferrari. Não é produzido, revisado ou endossado por nenhuma empresa de auditoria (KPMG, Deloitte, EY, PwC ou qualquer outra) — o formato segue a estrutura de um relatório de auditoria profissional (escopo, metodologia, recálculo independente, achados, opinião) apenas como referência de rigor e clareza.</p>
    </header>"""
    header_en = f"""
    <header class="audit-header">
      <div class="audit-kicker">Bolão do Ferrari · Automated Independent Technical Audit</div>
      <h1>Audit Report — Scoring &amp; Prize Payout Integrity</h1>
      <div class="audit-meta">
        <div><b>Scope:</b> 2026 World Cup — scoring, ranking, and prize mechanism</div>
        <div><b>Generated at:</b> {ts_en}</div>
        <div><b>Real entries audited:</b> {meta['entry_count']}</div>
        <div><b>Locked matches audited:</b> {meta['locked_count']} of 32</div>
        <div><b>Current pot:</b> ${meta['pot']}</div>
        <div><b>Opinion:</b> {opinion['en']}</div>
      </div>
      <p class="audit-disclaimer">This report is generated by Bolão do Ferrari's own automated verification system. It is not produced, reviewed, or endorsed by any audit firm (KPMG, Deloitte, EY, PwC, or otherwise) — the format follows the structure of a professional audit report (scope, methodology, independent recomputation, findings, opinion) only as a reference for rigor and clarity.</p>
    </header>"""
    header_es = f"""
    <header class="audit-header">
      <div class="audit-kicker">Bolão do Ferrari · Auditoría Técnica Independiente Automatizada</div>
      <h1>Informe de Auditoría — Integridad de Puntuación y Premiación</h1>
      <div class="audit-meta">
        <div><b>Alcance:</b> Copa del Mundo 2026 — puntuación, ranking y mecanismo de premiación</div>
        <div><b>Fecha/hora de generación:</b> {ts_es}</div>
        <div><b>Entradas reales auditadas:</b> {meta['entry_count']}</div>
        <div><b>Partidos bloqueados auditados:</b> {meta['locked_count']} de 32</div>
        <div><b>Bolsa actual:</b> ${meta['pot']}</div>
        <div><b>Opinión:</b> {opinion['es']}</div>
      </div>
      <p class="audit-disclaimer">Este informe es generado por un sistema de verificación automatizada propio de Bolão do Ferrari. No es producido, revisado ni avalado por ninguna firma de auditoría (KPMG, Deloitte, EY, PwC u otra) — el formato sigue la estructura de un informe de auditoría profesional (alcance, metodología, recálculo independiente, hallazgos, opinión) solo como referencia de rigor y claridad.</p>
    </header>"""

    exec_summary_pt = f"""<section class="audit-section exec-summary">
      <h2>Sumário executivo</h2>
      <p>Esta auditoria recalculou de forma independente a pontuação de todas as {meta['entry_count']} entradas reais do bolão, com base nos dados reais de produção (Supabase), sem reutilizar a lógica de pontuação do site ou do pipeline de e-mail — apenas os dados brutos (palpites, resultados, estrutura do bracket). Também verificou a integridade dos dados, a fórmula de pontuação, o mecanismo de premiação e os critérios de desempate documentados.</p>
      <p>{'<b>Nenhuma divergência foi encontrada</b> entre o recálculo independente e a pontuação oficial em nenhuma das ' + str(meta['entry_count']) + ' entradas auditadas.' if meta['all_pass'] else 'Foram encontrados itens que precisam de revisão — ver seções abaixo.'} Três problemas foram identificados e corrigidos nos últimos dias, antes deste relatório (seção H) — dois afetavam apenas uma prévia exibida durante partidas ao vivo (nunca a pontuação oficial), o terceiro afetava a pontuação oficial diretamente e já foi corrigido e comunicado aos participantes.</p>
      <p>Esta auditoria é publicada antes do resultado da Final (M104), como um compromisso de transparência: o mecanismo que vai decidir o pódio final e os valores em dinheiro amanhã já pode ser conferido hoje.</p>
    </section>"""
    exec_summary_en = f"""<section class="audit-section exec-summary">
      <h2>Executive summary</h2>
      <p>This audit independently recomputed the score of all {meta['entry_count']} real bolão entries, based on real production data (Supabase), without reusing the site's or the email pipeline's own scoring logic — only raw data (picks, results, bracket structure). It also verified data integrity, the scoring formula, the prize mechanism, and the documented tiebreak rules.</p>
      <p>{'<b>No discrepancies were found</b> between the independent recomputation and the official score for any of the ' + str(meta['entry_count']) + ' entries audited.' if meta['all_pass'] else 'Items requiring review were found — see the sections below.'} Three issues were identified and fixed over the past few days, before this report (section H) — two only affected a preview shown during live matches (never official scoring), the third affected official scoring directly and has already been fixed and communicated to participants.</p>
      <p>This audit is published before the Final's (M104) result, as a transparency commitment: the mechanism that will decide tomorrow's final podium and dollar amounts can already be checked today.</p>
    </section>"""
    exec_summary_es = f"""<section class="audit-section exec-summary">
      <h2>Resumen ejecutivo</h2>
      <p>Esta auditoría recalculó de forma independiente la puntuación de las {meta['entry_count']} entradas reales del bolão, con base en datos reales de producción (Supabase), sin reutilizar la lógica de puntuación del sitio ni del pipeline de correo — solo datos brutos (pronósticos, resultados, estructura del cuadro). También verificó la integridad de los datos, la fórmula de puntuación, el mecanismo de premiación y los criterios de desempate documentados.</p>
      <p>{'<b>No se encontraron discrepancias</b> entre el recálculo independiente y la puntuación oficial en ninguna de las ' + str(meta['entry_count']) + ' entradas auditadas.' if meta['all_pass'] else 'Se encontraron puntos que requieren revisión — ver las secciones a continuación.'} Se identificaron y corrigieron tres problemas en los últimos días, antes de este informe (sección H) — dos afectaban solo una vista previa mostrada durante partidos en vivo (nunca la puntuación oficial), el tercero afectaba la puntuación oficial directamente y ya fue corregido y comunicado a los participantes.</p>
      <p>Esta auditoría se publica antes del resultado de la Final (M104), como un compromiso de transparencia: el mecanismo que decidirá el podio final y los montos en dinero mañana ya puede verificarse hoy.</p>
    </section>"""

    detail_links_pt = f"""<section class="audit-section" style="border-left:4px solid #2563eb">
      <h2>🔍 Auditoria detalhada e transparência de código</h2>
      <p>Este resumo executivo tem propósito de leitura rápida. Para o nível de detalhe completo — cada palpite, cada partida, cada ponto — e o histórico completo de criação/edição de cada entrada, use os links abaixo:</p>
      <ul>
        <li><a href="audit-detail-picks.html"><b>📊 Auditoria por partida e por entrada</b></a> — palpite, resultado real e pontos ganhos em cada uma das 32 partidas, para cada uma das {meta['entry_count']} entradas reais (não é resumido — é o dado bruto completo, com índice navegável).</li>
        <li><a href="audit-detail-governance.html"><b>📋 Governança e histórico de edições</b></a> — data/hora de criação e última atualização de cada entrada, mais o histórico completo de mudanças (antes/depois de cada palpite alterado, IP completo, dispositivo, horário).</li>
        <li><b>Código-fonte:</b> este relatório e toda a lógica de pontuação são <a href="{GITHUB_REPO_URL}/bolao/copa2026/scripts/generate_audit_report.py">código aberto no GitHub</a> — <a href="{GITHUB_REPO_URL}/bolao/copa2026/scripts/send_result_email.py">pontuação/e-mail</a>, <a href="{GITHUB_REPO_URL}/bolao/copa2026/js/app.js">lógica do site</a>, <a href="{GITHUB_REPO_URL}/bolao/copa2026/scripts/audit_scoring.py">suíte de autoteste</a>, <a href="{GITHUB_REPO_URL}/bolao/copa2026/CHANGELOG.md">histórico completo de mudanças</a>.</li>
      </ul>
    </section>"""
    detail_links_en = f"""<section class="audit-section" style="border-left:4px solid #2563eb">
      <h2>🔍 Detailed audit and code transparency</h2>
      <p>This executive summary is meant for a quick read. For the full level of detail — every pick, every match, every point — and the complete creation/edit history of every entry, use the links below:</p>
      <ul>
        <li><a href="audit-detail-picks.html"><b>📊 Per-match, per-entry audit</b></a> — pick, real result, and points earned on each of the 32 matches, for each of the {meta['entry_count']} real entries (not summarized — the full raw data, with a navigable index).</li>
        <li><a href="audit-detail-governance.html"><b>📋 Governance and edit history</b></a> — creation date/time and last update for each entry, plus the complete change history (before/after for every changed pick, full IP, device, timestamp).</li>
        <li><b>Source code:</b> this report and all the scoring logic are <a href="{GITHUB_REPO_URL}/bolao/copa2026/scripts/generate_audit_report.py">open source on GitHub</a> — <a href="{GITHUB_REPO_URL}/bolao/copa2026/scripts/send_result_email.py">scoring/email</a>, <a href="{GITHUB_REPO_URL}/bolao/copa2026/js/app.js">site logic</a>, <a href="{GITHUB_REPO_URL}/bolao/copa2026/scripts/audit_scoring.py">self-test suite</a>, <a href="{GITHUB_REPO_URL}/bolao/copa2026/CHANGELOG.md">full change history</a>.</li>
      </ul>
    </section>"""
    detail_links_es = f"""<section class="audit-section" style="border-left:4px solid #2563eb">
      <h2>🔍 Auditoría detallada y transparencia de código</h2>
      <p>Este resumen ejecutivo es para una lectura rápida. Para el nivel de detalle completo — cada pronóstico, cada partido, cada punto — y el historial completo de creación/edición de cada entrada, usa los enlaces a continuación:</p>
      <ul>
        <li><a href="audit-detail-picks.html"><b>📊 Auditoría por partido y por entrada</b></a> — pronóstico, resultado real y puntos ganados en cada uno de los 32 partidos, para cada una de las {meta['entry_count']} entradas reales (no resumido — el dato bruto completo, con índice navegable).</li>
        <li><a href="audit-detail-governance.html"><b>📋 Gobernanza e historial de ediciones</b></a> — fecha/hora de creación y última actualización de cada entrada, más el historial completo de cambios (antes/después de cada pronóstico modificado, IP completa, dispositivo, horario).</li>
        <li><b>Código fuente:</b> este informe y toda la lógica de puntuación son <a href="{GITHUB_REPO_URL}/bolao/copa2026/scripts/generate_audit_report.py">código abierto en GitHub</a> — <a href="{GITHUB_REPO_URL}/bolao/copa2026/scripts/send_result_email.py">puntuación/correo</a>, <a href="{GITHUB_REPO_URL}/bolao/copa2026/js/app.js">lógica del sitio</a>, <a href="{GITHUB_REPO_URL}/bolao/copa2026/scripts/audit_scoring.py">suite de autopruebas</a>, <a href="{GITHUB_REPO_URL}/bolao/copa2026/CHANGELOG.md">historial completo de cambios</a>.</li>
      </ul>
    </section>"""

    signoff_pt = f"""<section class="audit-section signoff">
      <h2>Certificação</h2>
      <p>Certifico que os procedimentos descritos neste relatório foram executados de forma automatizada em {ts_pt}, contra os dados de produção do Bolão do Ferrari, e que os resultados apresentados refletem fielmente o recálculo obtido. Este relatório pode ser regenerado a qualquer momento executando <code>python3 bolao/scripts/generate_audit_report.py</code>.</p>
      <p class="signoff-name">Sistema de Auditoria Automatizada — Bolão do Ferrari</p>
    </section>"""
    signoff_en = f"""<section class="audit-section signoff">
      <h2>Certification</h2>
      <p>I certify that the procedures described in this report were executed automatically at {ts_en}, against Bolão do Ferrari's production data, and that the results shown faithfully reflect the recomputation obtained. This report can be regenerated at any time by running <code>python3 bolao/scripts/generate_audit_report.py</code>.</p>
      <p class="signoff-name">Automated Audit System — Bolão do Ferrari</p>
    </section>"""
    signoff_es = f"""<section class="audit-section signoff">
      <h2>Certificación</h2>
      <p>Certifico que los procedimientos descritos en este informe se ejecutaron de forma automatizada el {ts_es}, contra los datos de producción de Bolão do Ferrari, y que los resultados presentados reflejan fielmente el recálculo obtenido. Este informe puede regenerarse en cualquier momento ejecutando <code>python3 bolao/scripts/generate_audit_report.py</code>.</p>
      <p class="signoff-name">Sistema de Auditoría Automatizada — Bolão do Ferrari</p>
    </section>"""

    body_pt = header_pt + exec_summary_pt + detail_links_pt + sections_html("pt") + signoff_pt
    body_en = header_en + exec_summary_en + detail_links_en + sections_html("en") + signoff_en
    body_es = header_es + exec_summary_es + detail_links_es + sections_html("es") + signoff_es

    return f"""<!doctype html>
<html lang="pt-BR">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex,nofollow">
<title>Relatório de Auditoria — Bolão do Ferrari</title>
<style>
  :root {{ --green:#0d7a3f; --gold:#b45309; --border:#dde3e8; --bg:#f4f7fb; --bad:#b91c1c; }}
  * {{ box-sizing:border-box; }}
  body {{ font-family:Georgia,'Times New Roman',serif; background:var(--bg); color:#161b1f; margin:0; padding:0 16px 60px; }}
  .doc {{ max-width:900px; margin:0 auto; }}
  .lang-bar {{ position:sticky; top:0; background:#fff; border-bottom:1px solid var(--border); padding:12px 8px; margin-bottom:8px; display:flex; gap:8px; flex-wrap:wrap; justify-content:center; z-index:10; }}
  .lang-bar button {{ font-family:Arial,sans-serif; font-size:13px; font-weight:700; padding:8px 16px; border-radius:20px; border:1px solid var(--border); background:#fff; cursor:pointer; white-space:nowrap; }}
  .lang-bar button.active {{ background:var(--green); color:#fff; border-color:var(--green); }}
  .print-btn {{ font-family:Arial,sans-serif; font-size:13px; font-weight:700; padding:8px 16px; border-radius:20px; border:1px solid var(--border); background:#fff; cursor:pointer; white-space:nowrap; }}
  @media (max-width:420px) {{ .lang-bar button, .print-btn {{ font-size:12px; padding:8px 12px; }} }}
  .audit-header {{ background:#fff; border:1px solid var(--border); border-radius:14px; padding:28px 32px; margin:16px 0 20px; box-shadow:0 4px 24px #0001; }}
  .audit-kicker {{ font-family:Arial,sans-serif; font-size:12px; font-weight:800; text-transform:uppercase; letter-spacing:.08em; color:var(--green); margin-bottom:8px; }}
  .audit-header h1 {{ margin:0 0 16px; font-size:26px; }}
  .audit-meta {{ font-family:Arial,sans-serif; font-size:13px; display:grid; grid-template-columns:1fr 1fr; gap:6px 24px; background:var(--bg); border-radius:10px; padding:14px 16px; }}
  .audit-disclaimer {{ font-family:Arial,sans-serif; font-size:11px; color:#6b7280; margin:16px 0 0; line-height:1.5; }}
  .audit-section {{ background:#fff; border:1px solid var(--border); border-radius:14px; padding:22px 28px; margin-bottom:16px; box-shadow:0 2px 12px #0001; }}
  .audit-section h2 {{ font-size:18px; margin:0 0 12px; display:flex; align-items:center; gap:10px; flex-wrap:wrap; }}
  .badge {{ font-family:Arial,sans-serif; font-size:10px; font-weight:800; letter-spacing:.04em; padding:4px 10px; border-radius:20px; }}
  .badge-pass {{ background:#d1fae5; color:#065f46; }}
  .badge-remediated {{ background:#fef3c7; color:#92400e; }}
  .badge-info {{ background:#fee2e2; color:var(--bad); }}
  .section-body {{ font-size:14.5px; line-height:1.65; }}
  .section-body ul, .section-body ol {{ padding-left:22px; }}
  .section-body code {{ background:#f1f5f9; padding:1px 5px; border-radius:4px; font-size:.9em; }}
  .exec-summary {{ border-left:4px solid var(--green); }}
  .signoff {{ border-left:4px solid var(--gold); }}
  .signoff-name {{ font-style:italic; margin-top:18px; }}
  .audit-table {{ width:100%; border-collapse:collapse; font-family:Arial,sans-serif; font-size:12.5px; margin-top:10px; }}
  .audit-table th {{ background:#f1f5f9; text-align:left; padding:7px 10px; border-bottom:2px solid var(--border); }}
  .audit-table td {{ padding:6px 10px; border-bottom:1px solid var(--border); }}
  .audit-table td.num {{ text-align:center; font-weight:700; }}
  .audit-table .row-bad {{ background:#fee2e2; }}
  @media (max-width:640px) {{ .audit-meta {{ grid-template-columns:1fr; }} .audit-header, .audit-section {{ padding:18px; }} }}
  @media print {{ .lang-bar {{ display:none; }} body {{ background:#fff; }} .audit-header, .audit-section {{ box-shadow:none; border:1px solid #ccc; }} [data-lang]:not(.lang-active) {{ display:none !important; }} }}
  [data-lang] {{ display:none; }}
  [data-lang].lang-active {{ display:block; }}
</style>
</head>
<body>
<div class="doc">
  <div class="lang-bar">
    <button data-setlang="pt" class="active">🇧🇷 Português</button>
    <button data-setlang="en">🇺🇸 English</button>
    <button data-setlang="es">🇲🇽 Español</button>
    <button class="print-btn" onclick="window.print()">🖨️ Print / PDF</button>
  </div>
  <div data-lang="pt" class="lang-active">{body_pt}</div>
  <div data-lang="en">{body_en}</div>
  <div data-lang="es">{body_es}</div>
</div>
<script>
(function() {{
  var buttons = document.querySelectorAll('[data-setlang]');
  buttons.forEach(function(btn) {{
    btn.addEventListener('click', function() {{
      var lang = btn.getAttribute('data-setlang');
      document.querySelectorAll('[data-lang]').forEach(function(el) {{
        el.classList.toggle('lang-active', el.getAttribute('data-lang') === lang);
      }});
      buttons.forEach(function(b) {{ b.classList.toggle('active', b === btn); }});
      document.documentElement.lang = lang === 'pt' ? 'pt-BR' : lang === 'es' ? 'es' : 'en-US';
    }});
  }});
}})();
</script>
</body>
</html>"""


def main():
    print("Fetching live production state from Supabase...")
    state = sre.sb_fetch()
    locked_results = {k: v for k, v in (state.get("results") or {}).items() if v and v.get("advanceSide")}
    print(f"  {len(state.get('entries', []))} entries, {len(locked_results)} locked results")
    print("Running audit checks...")
    findings, meta = run_checks(state)
    for f in findings:
        print(f"  [{f.status.upper():10s}] {f.title['pt']}")

    print("Computing full picks traceability...")
    traceability = compute_picks_traceability(state, locked_results)
    print("Computing governance/edit-trail...")
    gov = compute_governance_trail(state)
    if gov["anomalies"]:
        print(f"  ⚠ {len(gov['anomalies'])} entries flagged: updatedAt differs from createdAt with no matching audit log record")

    print("Rendering trilingual executive summary...")
    html = render_report(findings, meta, state)
    with open(OUT_PATH, "w", encoding="utf-8") as fh:
        fh.write(html)
    print(f"✓ Written to {OUT_PATH}")

    print("Rendering picks detail page...")
    with open(PICKS_DETAIL_PATH, "w", encoding="utf-8") as fh:
        fh.write(render_picks_detail(traceability, meta))
    print(f"✓ Written to {PICKS_DETAIL_PATH}")

    print("Rendering governance detail page...")
    with open(GOVERNANCE_DETAIL_PATH, "w", encoding="utf-8") as fh:
        fh.write(render_governance_detail(gov, meta))
    print(f"✓ Written to {GOVERNANCE_DETAIL_PATH}")

    print(f"\n  All checks passed: {meta['all_pass']}")


if __name__ == "__main__":
    main()
