-- 012_seed_notification_history.sql — F7, migracao do historico legado.
--
-- Marca como ja NOTIFICADAS as rodadas que o estado legado prova terem sido comunicadas, para
-- que o primeiro catch-up sobre o ledger atomico nao reenvie nada. Sem isto, 20 rodadas
-- historicas apareceriam como candidatas.
--
-- PRE_FEATURE     = rodada encerrada antes de o recurso de e-mail existir; nunca teve e nunca
--                   deve ter e-mail.
-- LEGACY_MIGRATION = todos os canonicalFixtureIds constam em sentGameIds; foi de fato enviada.
--
-- O JSON legado em bolao_state.roundEmail PERMANECE INTACTO: e evidencia historica e a fonte
-- desta propria migracao. Nada e apagado.
--
-- Idempotente: on conflict do nothing. Reaplicar nao duplica nem sobrescreve.
--
-- ROLLBACK: delete from public.bolao_notif_jobs where pool_id='br2026' and event_type='round-results-history';

insert into public.bolao_notif_jobs (pool_id, entity_id, event_type, event_version, entry_ref, idempotency_key, status, sent_at, payload_snapshot, schema_version) values ('br2026', 'round-1', 'round-results-history', 1, 'HISTORICO', 'br2026:round-results:1:v1', 'sent', now(), '{"source":"PRE_FEATURE","evidence":"rodada encerrada em 2026-01-30T00:30:00+00:00, antes do epoch 2026-07-16T22:30:00Z"}'::jsonb, 1) on conflict (idempotency_key) do nothing;
insert into public.bolao_notif_jobs (pool_id, entity_id, event_type, event_version, entry_ref, idempotency_key, status, sent_at, payload_snapshot, schema_version) values ('br2026', 'round-2', 'round-results-history', 1, 'HISTORICO', 'br2026:round-results:2:v1', 'sent', now(), '{"source":"PRE_FEATURE","evidence":"rodada encerrada em 2026-02-19T22:30:00+00:00, antes do epoch 2026-07-16T22:30:00Z"}'::jsonb, 1) on conflict (idempotency_key) do nothing;
insert into public.bolao_notif_jobs (pool_id, entity_id, event_type, event_version, entry_ref, idempotency_key, status, sent_at, payload_snapshot, schema_version) values ('br2026', 'round-3', 'round-results-history', 1, 'HISTORICO', 'br2026:round-results:3:v1', 'sent', now(), '{"source":"PRE_FEATURE","evidence":"rodada encerrada em 2026-02-13T00:30:00+00:00, antes do epoch 2026-07-16T22:30:00Z"}'::jsonb, 1) on conflict (idempotency_key) do nothing;
insert into public.bolao_notif_jobs (pool_id, entity_id, event_type, event_version, entry_ref, idempotency_key, status, sent_at, payload_snapshot, schema_version) values ('br2026', 'round-4', 'round-results-history', 1, 'HISTORICO', 'br2026:round-results:4:v1', 'sent', now(), '{"source":"PRE_FEATURE","evidence":"rodada encerrada em 2026-02-26T22:00:00+00:00, antes do epoch 2026-07-16T22:30:00Z"}'::jsonb, 1) on conflict (idempotency_key) do nothing;
insert into public.bolao_notif_jobs (pool_id, entity_id, event_type, event_version, entry_ref, idempotency_key, status, sent_at, payload_snapshot, schema_version) values ('br2026', 'round-5', 'round-results-history', 1, 'HISTORICO', 'br2026:round-results:5:v1', 'sent', now(), '{"source":"PRE_FEATURE","evidence":"rodada encerrada em 2026-03-29T22:30:00+00:00, antes do epoch 2026-07-16T22:30:00Z"}'::jsonb, 1) on conflict (idempotency_key) do nothing;
insert into public.bolao_notif_jobs (pool_id, entity_id, event_type, event_version, entry_ref, idempotency_key, status, sent_at, payload_snapshot, schema_version) values ('br2026', 'round-6', 'round-results-history', 1, 'HISTORICO', 'br2026:round-results:6:v1', 'sent', now(), '{"source":"PRE_FEATURE","evidence":"rodada encerrada em 2026-03-16T23:00:00+00:00, antes do epoch 2026-07-16T22:30:00Z"}'::jsonb, 1) on conflict (idempotency_key) do nothing;
insert into public.bolao_notif_jobs (pool_id, entity_id, event_type, event_version, entry_ref, idempotency_key, status, sent_at, payload_snapshot, schema_version) values ('br2026', 'round-7', 'round-results-history', 1, 'HISTORICO', 'br2026:round-results:7:v1', 'sent', now(), '{"source":"PRE_FEATURE","evidence":"rodada encerrada em 2026-03-20T00:30:00+00:00, antes do epoch 2026-07-16T22:30:00Z"}'::jsonb, 1) on conflict (idempotency_key) do nothing;
insert into public.bolao_notif_jobs (pool_id, entity_id, event_type, event_version, entry_ref, idempotency_key, status, sent_at, payload_snapshot, schema_version) values ('br2026', 'round-8', 'round-results-history', 1, 'HISTORICO', 'br2026:round-results:8:v1', 'sent', now(), '{"source":"PRE_FEATURE","evidence":"rodada encerrada em 2026-03-22T23:30:00+00:00, antes do epoch 2026-07-16T22:30:00Z"}'::jsonb, 1) on conflict (idempotency_key) do nothing;
insert into public.bolao_notif_jobs (pool_id, entity_id, event_type, event_version, entry_ref, idempotency_key, status, sent_at, payload_snapshot, schema_version) values ('br2026', 'round-9', 'round-results-history', 1, 'HISTORICO', 'br2026:round-results:9:v1', 'sent', now(), '{"source":"PRE_FEATURE","evidence":"rodada encerrada em 2026-04-03T00:30:00+00:00, antes do epoch 2026-07-16T22:30:00Z"}'::jsonb, 1) on conflict (idempotency_key) do nothing;
insert into public.bolao_notif_jobs (pool_id, entity_id, event_type, event_version, entry_ref, idempotency_key, status, sent_at, payload_snapshot, schema_version) values ('br2026', 'round-10', 'round-results-history', 1, 'HISTORICO', 'br2026:round-results:10:v1', 'sent', now(), '{"source":"PRE_FEATURE","evidence":"rodada encerrada em 2026-04-05T23:30:00+00:00, antes do epoch 2026-07-16T22:30:00Z"}'::jsonb, 1) on conflict (idempotency_key) do nothing;
insert into public.bolao_notif_jobs (pool_id, entity_id, event_type, event_version, entry_ref, idempotency_key, status, sent_at, payload_snapshot, schema_version) values ('br2026', 'round-11', 'round-results-history', 1, 'HISTORICO', 'br2026:round-results:11:v1', 'sent', now(), '{"source":"PRE_FEATURE","evidence":"rodada encerrada em 2026-04-12T21:30:00+00:00, antes do epoch 2026-07-16T22:30:00Z"}'::jsonb, 1) on conflict (idempotency_key) do nothing;
insert into public.bolao_notif_jobs (pool_id, entity_id, event_type, event_version, entry_ref, idempotency_key, status, sent_at, payload_snapshot, schema_version) values ('br2026', 'round-12', 'round-results-history', 1, 'HISTORICO', 'br2026:round-results:12:v1', 'sent', now(), '{"source":"PRE_FEATURE","evidence":"rodada encerrada em 2026-04-19T22:30:00+00:00, antes do epoch 2026-07-16T22:30:00Z"}'::jsonb, 1) on conflict (idempotency_key) do nothing;
insert into public.bolao_notif_jobs (pool_id, entity_id, event_type, event_version, entry_ref, idempotency_key, status, sent_at, payload_snapshot, schema_version) values ('br2026', 'round-13', 'round-results-history', 1, 'HISTORICO', 'br2026:round-results:13:v1', 'sent', now(), '{"source":"PRE_FEATURE","evidence":"rodada encerrada em 2026-04-26T23:30:00+00:00, antes do epoch 2026-07-16T22:30:00Z"}'::jsonb, 1) on conflict (idempotency_key) do nothing;
insert into public.bolao_notif_jobs (pool_id, entity_id, event_type, event_version, entry_ref, idempotency_key, status, sent_at, payload_snapshot, schema_version) values ('br2026', 'round-14', 'round-results-history', 1, 'HISTORICO', 'br2026:round-results:14:v1', 'sent', now(), '{"source":"PRE_FEATURE","evidence":"rodada encerrada em 2026-05-03T23:30:00+00:00, antes do epoch 2026-07-16T22:30:00Z"}'::jsonb, 1) on conflict (idempotency_key) do nothing;
insert into public.bolao_notif_jobs (pool_id, entity_id, event_type, event_version, entry_ref, idempotency_key, status, sent_at, payload_snapshot, schema_version) values ('br2026', 'round-15', 'round-results-history', 1, 'HISTORICO', 'br2026:round-results:15:v1', 'sent', now(), '{"source":"PRE_FEATURE","evidence":"rodada encerrada em 2026-05-10T23:30:00+00:00, antes do epoch 2026-07-16T22:30:00Z"}'::jsonb, 1) on conflict (idempotency_key) do nothing;
insert into public.bolao_notif_jobs (pool_id, entity_id, event_type, event_version, entry_ref, idempotency_key, status, sent_at, payload_snapshot, schema_version) values ('br2026', 'round-16', 'round-results-history', 1, 'HISTORICO', 'br2026:round-results:16:v1', 'sent', now(), '{"source":"PRE_FEATURE","evidence":"rodada encerrada em 2026-05-17T22:30:00+00:00, antes do epoch 2026-07-16T22:30:00Z"}'::jsonb, 1) on conflict (idempotency_key) do nothing;
insert into public.bolao_notif_jobs (pool_id, entity_id, event_type, event_version, entry_ref, idempotency_key, status, sent_at, payload_snapshot, schema_version) values ('br2026', 'round-17', 'round-results-history', 1, 'HISTORICO', 'br2026:round-results:17:v1', 'sent', now(), '{"source":"PRE_FEATURE","evidence":"rodada encerrada em 2026-05-25T23:00:00+00:00, antes do epoch 2026-07-16T22:30:00Z"}'::jsonb, 1) on conflict (idempotency_key) do nothing;
insert into public.bolao_notif_jobs (pool_id, entity_id, event_type, event_version, entry_ref, idempotency_key, status, sent_at, payload_snapshot, schema_version) values ('br2026', 'round-18', 'round-results-history', 1, 'HISTORICO', 'br2026:round-results:18:v1', 'sent', now(), '{"source":"PRE_FEATURE","evidence":"rodada encerrada em 2026-05-31T23:30:00+00:00, antes do epoch 2026-07-16T22:30:00Z"}'::jsonb, 1) on conflict (idempotency_key) do nothing;
insert into public.bolao_notif_jobs (pool_id, entity_id, event_type, event_version, entry_ref, idempotency_key, status, sent_at, payload_snapshot, schema_version) values ('br2026', 'round-19', 'round-results-history', 1, 'HISTORICO', 'br2026:round-results:19:v1', 'sent', now(), '{"source":"LEGACY_MIGRATION","evidence":"todos os canonicalFixtureIds constam em sentGameIds"}'::jsonb, 1) on conflict (idempotency_key) do nothing;
insert into public.bolao_notif_jobs (pool_id, entity_id, event_type, event_version, entry_ref, idempotency_key, status, sent_at, payload_snapshot, schema_version) values ('br2026', 'round-20', 'round-results-history', 1, 'HISTORICO', 'br2026:round-results:20:v1', 'sent', now(), '{"source":"LEGACY_MIGRATION","evidence":"todos os canonicalFixtureIds constam em sentGameIds"}'::jsonb, 1) on conflict (idempotency_key) do nothing;
